# Assignment 1 {#tha1}

## Due Date: 19-01-2023

## Instructions

Please read through the Getting Started and the Basics pages before working on this assignment, especially if you have no background in R.

1. Download R.
1. Download RStudio.
1. Set working directory. 
1. Suppose we have the starting monthly salary of 10 men and 10 women (see **Data** section below). Enter the data provided into a data frame where one column represents the biological sex of the individual (call this column `BioSex`) and the other column represents the starting monthly salary (call this column `Salary`) of the individual. Check that you have 20 rows (one for each individual) and 2 columns (one for each variable).
1. Save the data frame into a .csv file. Name this file `data.csv`.
1. For each step above, put in comments using the # sign so that you know what was done. (e.g., # set working directory)
1. When you’re done with the above, copy and paste your R script into a word document. Submit the word document in the eLearn Assignment for 1 point.

_Note._ Answers will be released on eLearn the day after this assignment is due.

## Data

```{r echo = FALSE}

Man <- c(3530, 4730, 4330, 3560, 4050, 4880, 4190, 3620, 3530, 5070)
Woman <- c(3790, 2720, 3170, 3320, 3190, 2890, 2920, 3390, 3790, 3680)
data <- cbind(Man, Woman)
knitr::kable(data, align = c('c', 'c'))

```