# Assignment 1 {#tha1}

## Due Date: DD-MM-YYYY

## Instructions

1. Download the data file here: [SWB.csv](SWB.csv).
1. Open up a new script file in RStudio using `Ctrl/Cmd + Shift + N`. 
1. Set working directory using `setwd()`.
1. Load `tidyverse` using `library()`.
1. Read in the data file `SWB.csv` using `read_csv()` or `read.csv()`.
1. Examine the dataset with `glimpse()` or `View()` or `str(). 
1. Convert `marital_status` and `have_children` from integer to factor using `factor()`. Add value labels to the factors. See the legend below to see how each variable is coded. 
1. Use `glimpse()` or `str()` to check that the variables are indeed converted to factors.
1. Create a subset of the dataset of only married parents (i.e., married people who have children). Further subset the dataset such that only the variables `swls2021_1`, `swls2021_2`, `swls2021_3`, `swls2021_4`, and `swls2021_5` are in the dataset. You should have 68 rows and 5 columns in this subset.
1. Using this subset, compute the average of `swls2021_1`, `swls2021_2`, `swls2021_3`, `swls2021_4`, and `swls2021_5` for each person. Call this variable `swls2021_avg`. 
1. Using this subset, get the following summary statistics for `swls2021_avg`: maximum, minimum, mean, and sd. Check that the maximum is 5.4, the minimum is 2.6, the mean is 4.18, and the sd is 0.707.
1. For each step above, put in comments using the # sign so that you know what was done. (e.g., # set working directory, # load packages)
1. When you’re done with the above, copy and paste your R script into a word document. Submit the word document in the eLearn Assignment for 1 point.

## Legend

| Variable Name   | Variable Label | Value Label | 
|:-------|:----|:----------------|
|pin|participant identification number||
|gender|gender|0 = male, 1 = female|
|marital_status| marital status| 1 = married, 2 = divorced, 3 = widowed|
|have_children|parental status | 0 = no children, 1 = have children|
|mvs_1| My life would be better if I own certain things I don't have.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_2| The things I own say a lot about how well I'm doing.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_3| I'd be happier if I could afford to buy more things.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_4| It bothers me that I can't afford to buy things I'd like.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_5| Buying things gives me a lot of pleasure.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_6| I admire people who own expensive homes, cars, clothes. | 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_7| I like to own things that impress people.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_8| I like a lot of luxury in my life.| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|mvs_9| I try to keep my life simple, as far as possessions are concerned. (R)| 1 = strongly disagree, 2 = disagree, 3 = neither disagree nor agree, 4 = agree, 5 = strongly agree|
|swls2019_1|In most ways my life is close to my ideal. (2019)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2019_2|The conditions of my life are excellent. (2019)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2019_3|I am satisfied with my life. (2019)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2019_4|So far I have gotten the important things I want in life. (2019) |1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2019_5|In most ways my life is close to my ideal. (2019)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2021_1|In most ways my life is close to my ideal. (2021)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2021_2|The conditions of my life are excellent. (2021)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2021_3|I am satisfied with my life. (2021)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2021_4|So far I have gotten the important things I want in life. (2021) |1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|
|swls2021_5|In most ways my life is close to my ideal. (2021)|1 = strongly disagree, 2 = disagree, 3 = slightly disagree, 4 = neither disagree nor agree, 5 = slightly agree, 6 = agree, 7 = strongly agree|

## Check Your Results With Mine

```{r echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}

# Set working directory
# setwd("C:/Users/Win10/Desktop/R")

# Load packages
library(tidyverse)

# Set options 
options(scipen = 999) # Turn off scientific notation 
options(digits = 9) # Display results to 9 dp's

# Read .csv file
data <- read_csv("SWB.csv")

# Take a look at the variable names and types
glimpse(data)

# Convert integer to factor and adding value labels to the factor.
data$marital_status <- factor(data$marital_status, levels = c(1, 2, 3), labels = c("married", "divorced", "widowed"))
data$have_children <- factor(data$have_children, levels = c(0, 1), labels = c("no", "yes"))

# Check variables are now factors
glimpse(data$marital_status)
glimpse(data$have_children)

# Create subset 
subset <- data %>% 
  filter(marital_status == "married" & have_children == "yes") %>% 
  select(swls2021_1:swls2021_5)

# Take a look at the variable names and types
glimpse(subset)

# Compute rowMeans
subset <- subset %>% 
  mutate(swls2021_avg = rowMeans(across(c(swls2021_1:swls2021_5)))) 

# Get summary statistics
subset %>% 
  summarise(avg_swls = mean(swls2021_avg), 
            min_swls = min(swls2021_avg), 
            max_swls = max(swls2021_avg), 
            sd_swls = sd(swls2021_avg))

```

