--- 
title: "PSYC208 Take Home Assignments"
author: "Huey Woon LEE"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: hueywoon/assignment
description: "This website contains materials related to the take home assignments used in my PSYC208 class."
---

# Introduction {-}

This website contains materials related to the take home assignments used in my PSYC208 class. These assignments are graded on a PASS/FAIL basis. If the assignment is correctly done, the assignment is marked as PASS; otherwise, it is marked as FAIL. Unless there are exceptional circumstances (please inform TA or me), responses submitted after a grace period of 5 minutes will also be graded as FAIL. 

To complete the take home assignments, you will need R and RStudio. R is a programming language for statistical computing and RStudio is an integrated development environment to write and run code written in R.

## Install R and RStudio for Windows {-}

### Install R {-}
1.	Open an internet browser and go to [https://www.r-project.org/](https://www.r-project.org/).
2.	Click the "download R" link in the middle of the page under "Getting Started."
3.	Select a CRAN location (a mirror site) and click the corresponding link.  
4.	Click on the "Download R for Windows" link at the top of the page.  
5.	Click on the "install R for the first time" link at the top of the page.
6.	Click "Download R for Windows" and save the executable file somewhere on your computer.  Run the .exe file and follow the installation instructions.  
7.	Now that R is installed, you need to download and install RStudio. 

### Install RStudio {-}
1.	Go to www.rstudio.com and click on the "Download RStudio" button.
2.	Click on "Download RStudio Desktop."
3.	Click on the version recommended for your system, or the latest Windows version, and save the executable file.  Run the .exe file and follow the installation instructions

## Install R and RStudio for Mac {-}

### Install R {-}
1.	Open an internet browser and go to [https://www.r-project.org/](https://www.r-project.org/).
2.	Click the "download R" link in the middle of the page under "Getting Started."
3.	Select a CRAN location (a mirror site) and click the corresponding link.
4.	Click on the "Download R for (Mac) OS X" link at the top of the page.
5.	Click on the file containing the latest version of R under "Files."
6.	Save the .pkg file, double-click it to open, and follow the installation instructions.
7.	Now that R is installed, you need to download and install RStudio.

### Install RStudio {-}
1.	Go to www.rstudio.com and click on the "Download RStudio" button.
2.	Click on "Download RStudio Desktop."
3.	Click on the version recommended for your system, or the latest Mac version, save the .dmg file on your computer, double-click it to open, and then drag and drop it to your applications folder.     