<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Hypothesis Testing | PSYC208 R Companion Website</title>
  <meta name="description" content="This is the companion website to my PSYC208 class." />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Hypothesis Testing | PSYC208 R Companion Website" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the companion website to my PSYC208 class." />
  <meta name="github-repo" content="hueywoon/assignment" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Hypothesis Testing | PSYC208 R Companion Website" />
  
  <meta name="twitter:description" content="This is the companion website to my PSYC208 class." />
  

<meta name="author" content="Huey Woon LEE" />


<meta name="date" content="2023-01-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tha3.html"/>
<link rel="next" href="tha4.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC208 R Companion Website</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About This Website</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#install-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#the-rstudio-interface"><i class="fa fa-check"></i><b>1.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#r-script"><i class="fa fa-check"></i><b>1.3</b> R Script</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#some-tips-and-tricks"><i class="fa fa-check"></i><b>1.4</b> Some Tips and Tricks</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#softwrap-long-lines"><i class="fa fa-check"></i><b>1.4.1</b> Softwrap Long Lines</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#make-notes-or-comments"><i class="fa fa-check"></i><b>1.4.2</b> Make Notes or Comments</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#style-guide"><i class="fa fa-check"></i><b>1.4.3</b> Style Guide</a></li>
<li class="chapter" data-level="1.4.4" data-path="getting-started.html"><a href="getting-started.html#setting-working-directory"><i class="fa fa-check"></i><b>1.4.4</b> Setting working directory</a></li>
<li class="chapter" data-level="1.4.5" data-path="getting-started.html"><a href="getting-started.html#using-r-projects"><i class="fa fa-check"></i><b>1.4.5</b> Using R Projects</a></li>
<li class="chapter" data-level="1.4.6" data-path="getting-started.html"><a href="getting-started.html#debugging"><i class="fa fa-check"></i><b>1.4.6</b> Debugging</a></li>
<li class="chapter" data-level="1.4.7" data-path="getting-started.html"><a href="getting-started.html#last-words"><i class="fa fa-check"></i><b>1.4.7</b> Last Words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#some-basic-commands"><i class="fa fa-check"></i><b>2.1</b> Some Basic Commands</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#typing-and-executing-commands"><i class="fa fa-check"></i><b>2.2</b> Typing and Executing Commands</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#entering-data-directly-into-r"><i class="fa fa-check"></i><b>2.3</b> Entering Data Directly Into R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tha1.html"><a href="tha1.html"><i class="fa fa-check"></i><b>3</b> Assignment 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tha1.html"><a href="tha1.html#due-date-19-01-2023"><i class="fa fa-check"></i><b>3.1</b> Due Date: 19-01-2023</a></li>
<li class="chapter" data-level="3.2" data-path="tha1.html"><a href="tha1.html#instructions"><i class="fa fa-check"></i><b>3.2</b> Instructions</a></li>
<li class="chapter" data-level="3.3" data-path="tha1.html"><a href="tha1.html#data"><i class="fa fa-check"></i><b>3.3</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>4</b> Using tidyverse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tidyverse.html"><a href="tidyverse.html#installing-and-loading-tidyverse"><i class="fa fa-check"></i><b>4.1</b> Installing and Loading tidyverse</a></li>
<li class="chapter" data-level="4.2" data-path="tidyverse.html"><a href="tidyverse.html#import-data"><i class="fa fa-check"></i><b>4.2</b> Import Data</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="tidyverse.html"><a href="tidyverse.html#swb-dataset"><i class="fa fa-check"></i><b>4.2.1</b> SWB Dataset</a></li>
<li class="chapter" data-level="4.2.2" data-path="tidyverse.html"><a href="tidyverse.html#check-imported-dataset"><i class="fa fa-check"></i><b>4.2.2</b> Check Imported Dataset</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="tidyverse.html"><a href="tidyverse.html#factors"><i class="fa fa-check"></i><b>4.3</b> Factors</a></li>
<li class="chapter" data-level="4.4" data-path="tidyverse.html"><a href="tidyverse.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>4.4</b> Data Wrangling With dplyr</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="tidyverse.html"><a href="tidyverse.html#select"><i class="fa fa-check"></i><b>4.4.1</b> Select()</a></li>
<li class="chapter" data-level="4.4.2" data-path="tidyverse.html"><a href="tidyverse.html#filter"><i class="fa fa-check"></i><b>4.4.2</b> Filter()</a></li>
<li class="chapter" data-level="4.4.3" data-path="tidyverse.html"><a href="tidyverse.html#mutate"><i class="fa fa-check"></i><b>4.4.3</b> Mutate()</a></li>
<li class="chapter" data-level="4.4.4" data-path="tidyverse.html"><a href="tidyverse.html#summarise"><i class="fa fa-check"></i><b>4.4.4</b> Summarise()</a></li>
<li class="chapter" data-level="4.4.5" data-path="tidyverse.html"><a href="tidyverse.html#group_by"><i class="fa fa-check"></i><b>4.4.5</b> Group_by()</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="tidyverse.html"><a href="tidyverse.html#tables-and-plots-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Tables and Plots with ggplot2</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="tidyverse.html"><a href="tidyverse.html#frequency-tables"><i class="fa fa-check"></i><b>4.5.1</b> Frequency Tables</a></li>
<li class="chapter" data-level="4.5.2" data-path="tidyverse.html"><a href="tidyverse.html#bar-plots-with-ggplot2"><i class="fa fa-check"></i><b>4.5.2</b> Bar Plots with ggplot2</a></li>
<li class="chapter" data-level="4.5.3" data-path="tidyverse.html"><a href="tidyverse.html#histograms-with-ggplot2"><i class="fa fa-check"></i><b>4.5.3</b> Histograms with ggplot2</a></li>
<li class="chapter" data-level="4.5.4" data-path="tidyverse.html"><a href="tidyverse.html#scatterplot-with-ggplot2"><i class="fa fa-check"></i><b>4.5.4</b> Scatterplot with ggplot2</a></li>
<li class="chapter" data-level="4.5.5" data-path="tidyverse.html"><a href="tidyverse.html#last-words-1"><i class="fa fa-check"></i><b>4.5.5</b> Last Words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tha2.html"><a href="tha2.html"><i class="fa fa-check"></i><b>5</b> Assignment 2</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tha2.html"><a href="tha2.html#due-date-26-01-2023"><i class="fa fa-check"></i><b>5.1</b> Due Date: 26-01-2023</a></li>
<li class="chapter" data-level="5.2" data-path="tha2.html"><a href="tha2.html#instructions-1"><i class="fa fa-check"></i><b>5.2</b> Instructions</a></li>
<li class="chapter" data-level="5.3" data-path="tha2.html"><a href="tha2.html#legend"><i class="fa fa-check"></i><b>5.3</b> Legend</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="scale.html"><a href="scale.html"><i class="fa fa-check"></i><b>6</b> Multi-Item Measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="scale.html"><a href="scale.html#overview"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="scale.html"><a href="scale.html#dataset"><i class="fa fa-check"></i><b>6.2</b> Dataset</a></li>
<li class="chapter" data-level="6.3" data-path="scale.html"><a href="scale.html#check-the-pattern-of-responses-correlation-coefficient"><i class="fa fa-check"></i><b>6.3</b> Check the Pattern of Responses: Correlation Coefficient</a></li>
<li class="chapter" data-level="6.4" data-path="scale.html"><a href="scale.html#reliability-analysis-cronbachs-alpha"><i class="fa fa-check"></i><b>6.4</b> Reliability Analysis: Cronbach’s Alpha</a></li>
<li class="chapter" data-level="6.5" data-path="scale.html"><a href="scale.html#compute-the-average-score-for-the-scale"><i class="fa fa-check"></i><b>6.5</b> Compute the average score for the scale</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tha3.html"><a href="tha3.html"><i class="fa fa-check"></i><b>7</b> Assignment 3</a>
<ul>
<li class="chapter" data-level="7.1" data-path="tha3.html"><a href="tha3.html#due-date-02-02-2023"><i class="fa fa-check"></i><b>7.1</b> Due Date: 02-02-2023</a></li>
<li class="chapter" data-level="7.2" data-path="tha3.html"><a href="tha3.html#instructions-2"><i class="fa fa-check"></i><b>7.2</b> Instructions</a></li>
<li class="chapter" data-level="7.3" data-path="tha3.html"><a href="tha3.html#legend-1"><i class="fa fa-check"></i><b>7.3</b> Legend</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="hypotest.html"><a href="hypotest.html"><i class="fa fa-check"></i><b>8</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="hypotest.html"><a href="hypotest.html#overview-1"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="hypotest.html"><a href="hypotest.html#load-packages-and-dataset"><i class="fa fa-check"></i><b>8.2</b> Load Packages and Dataset</a></li>
<li class="chapter" data-level="8.3" data-path="hypotest.html"><a href="hypotest.html#scientific-notation"><i class="fa fa-check"></i><b>8.3</b> Scientific Notation</a></li>
<li class="chapter" data-level="8.4" data-path="hypotest.html"><a href="hypotest.html#one-sample-t-test"><i class="fa fa-check"></i><b>8.4</b> One-Sample T Test</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="hypotest.html"><a href="hypotest.html#when-to-use-a-one-sample-t-test"><i class="fa fa-check"></i><b>8.4.1</b> When to Use A One-Sample T Test</a></li>
<li class="chapter" data-level="8.4.2" data-path="hypotest.html"><a href="hypotest.html#conducting-and-interpreting-the-one-sample-t-test"><i class="fa fa-check"></i><b>8.4.2</b> Conducting and Interpreting the One-Sample T Test</a></li>
<li class="chapter" data-level="8.4.3" data-path="hypotest.html"><a href="hypotest.html#effect-size-cohens-d"><i class="fa fa-check"></i><b>8.4.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="hypotest.html"><a href="hypotest.html#correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5</b> Correlated Groups T Test</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="hypotest.html"><a href="hypotest.html#when-to-use-a-correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5.1</b> When to Use A Correlated Groups T Test</a></li>
<li class="chapter" data-level="8.5.2" data-path="hypotest.html"><a href="hypotest.html#conducting-and-interpreting-the-correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5.2</b> Conducting and Interpreting the Correlated Groups T Test</a></li>
<li class="chapter" data-level="8.5.3" data-path="hypotest.html"><a href="hypotest.html#effect-size-cohens-d-1"><i class="fa fa-check"></i><b>8.5.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="hypotest.html"><a href="hypotest.html#independent-groups-t-test"><i class="fa fa-check"></i><b>8.6</b> Independent Groups T Test</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="hypotest.html"><a href="hypotest.html#when-to-use-an-independent-groups-t-test"><i class="fa fa-check"></i><b>8.6.1</b> When to Use An Independent Groups T Test</a></li>
<li class="chapter" data-level="8.6.2" data-path="hypotest.html"><a href="hypotest.html#conducting-and-interpreting-the-independent-groups-t-test"><i class="fa fa-check"></i><b>8.6.2</b> Conducting and Interpreting the Independent Groups T Test</a></li>
<li class="chapter" data-level="8.6.3" data-path="hypotest.html"><a href="hypotest.html#effect-size-cohens-d-2"><i class="fa fa-check"></i><b>8.6.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="hypotest.html"><a href="hypotest.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.7</b> One-Way Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="8.8" data-path="hypotest.html"><a href="hypotest.html#two-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.8</b> Two-Way Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="8.9" data-path="hypotest.html"><a href="hypotest.html#correlation"><i class="fa fa-check"></i><b>8.9</b> Correlation</a></li>
<li class="chapter" data-level="8.10" data-path="hypotest.html"><a href="hypotest.html#regression"><i class="fa fa-check"></i><b>8.10</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tha4.html"><a href="tha4.html"><i class="fa fa-check"></i><b>9</b> Remaining Assignments</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC208 R Companion Website</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypotest" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Hypothesis Testing<a href="hypotest.html#hypotest" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="overview-1" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Overview<a href="hypotest.html#overview-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The bulk of what we cover in PSYC208 is hypothesis testing.</p>
<p>This section guides you through the steps of conducting the various hypothesis tests. This only serves as an overview for students who are interested to read ahead. I will demonstrate how to conduct the hypothesis tests in class as well as how to interpret the results.</p>
<p>To illustrate the various tests, we will use the same hypothetical dataset, <code>SWB.csv</code> as before. To follow along, please download the dataset: <a href="SWB.csv">SWB.csv</a>.</p>
</div>
<div id="load-packages-and-dataset" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Load Packages and Dataset<a href="hypotest.html#load-packages-and-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="hypotest.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb77-2"><a href="hypotest.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb77-3"><a href="hypotest.html#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb77-4"><a href="hypotest.html#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="hypotest.html#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the dataset</span></span>
<span id="cb77-6"><a href="hypotest.html#cb77-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;SWB.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="scientific-notation" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Scientific Notation<a href="hypotest.html#scientific-notation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to loading the packages and reading in the data file, it might also be helpful to run the code below to turn off scientific notation.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="hypotest.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set options </span></span>
<span id="cb78-2"><a href="hypotest.html#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># Turn off scientific notation </span></span>
<span id="cb78-3"><a href="hypotest.html#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">9</span>) <span class="co"># Display results to 9 decimal places</span></span></code></pre></div>
<p>Scientific notation is a way of expressing numbers that are very large or very small. It usually takes the form of <code>m × 10^n</code> for very large numbers and <code>m × 10^-n</code> for very small numbers, where <code>^</code> stands for “to the power of”. So, suppose we have the following number: 0.000000000000000477. In scientific notation, this would be represented as<code>4.77 x 10^-16</code>. Alternatively, it might be represented as <code>4.77e-16</code>. They mean the same thing.</p>
<p>By default, R presents very small or very large numbers in scientific notation. However, this can be difficult to understand for people who don’t use scientific notation in their daily lives. I confess I have difficulty with scientific notation myself so I usually turn the scientific notation off. It’s really a matter of personal choice whether you want to turn it off or not.</p>
<p>And now, let’s begin with the hypothesis tests!</p>
</div>
<div id="one-sample-t-test" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> One-Sample T Test<a href="hypotest.html#one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="when-to-use-a-one-sample-t-test" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> When to Use A One-Sample T Test<a href="hypotest.html#when-to-use-a-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use a one-sample t test when we want to compare the data from one group to some hypothesised mean. You can think of it as taking a set of observations or scores and then comparing it to some value.</p>
<p>So, suppose we’re interested to know whether on average, in 2019, people were more or less satisfied with their lives than the neutral value of 4. (Why 4? Well, in this data set, the satisfaction with life items were measured on a 7-point scale, where 4 is the neutral point.) To answer this question, we will conduct a one-sample t test.</p>
</div>
<div id="conducting-and-interpreting-the-one-sample-t-test" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Conducting and Interpreting the One-Sample T Test<a href="hypotest.html#conducting-and-interpreting-the-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before jumping into any hypothesis testing, though, it is good practice to first get the descriptive statistics for the variable(s) you’re investigating. At the minimum, you should get the mean and the standard deviation. (Anyway, you need to report means and standard deviations in APA style write-up!) I often also like to look at the minimum and maximum values to make sure the values are not out of ordinary (e.g., a value of -999 might throw up some red flags if, say, the likert scale only comprises values from 1 to 7).</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="hypotest.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average satisfaction with life score in 2019 for each participant</span></span>
<span id="cb79-2"><a href="hypotest.html#cb79-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb79-3"><a href="hypotest.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swls2019_avg =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(swls2019_1<span class="sc">:</span>swls2019_5))))</span>
<span id="cb79-4"><a href="hypotest.html#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="hypotest.html#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the descriptives</span></span>
<span id="cb79-6"><a href="hypotest.html#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(data<span class="sc">$</span>swls2019_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 4.35 0.77    4.4    4.33 0.89   2   6     4  0.1    -0.48 0.04</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="hypotest.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the one-sample t test to compare the satisfaction with life score in 2019 against the neutral point of 4</span></span>
<span id="cb81-2"><a href="hypotest.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co"># x = data$swls2019_avg tells R the variable we&#39;re interested in</span></span>
<span id="cb81-3"><a href="hypotest.html#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative = c(&quot;two-sided&quot;) tells R we want to conduct a two-tailed test (in my class, we ALWAYS conduct a two-tailed test)</span></span>
<span id="cb81-4"><a href="hypotest.html#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co"># mu = 4 tells R the value we&#39;re comparing to</span></span>
<span id="cb81-5"><a href="hypotest.html#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="co"># paired = FALSE tells R that each observation comes from different individuals (i.e., they are not &quot;paired&quot;)</span></span>
<span id="cb81-6"><a href="hypotest.html#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="co"># conf.level = 0.95 tells R we want the 95% confidence level. If we use alpha = .05, then the confidence level is 0.95. </span></span>
<span id="cb81-7"><a href="hypotest.html#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> data<span class="sc">$</span>swls2019_avg, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">4</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$swls2019_avg
## t = 8.530937, df = 342, p-value = 0.000000000000000477477
## alternative hypothesis: true mean is not equal to 4
## 95 percent confidence interval:
##  4.27188244 4.43482310
## sample estimates:
##  mean of x 
## 4.35335277</code></pre>
<p>The results tell you that the average of <code>swls2019_avg</code> is 4.35 (but notice it doesn’t tell you any other descriptive statistics like standard deviation or maximum, so it’s still important to get the descriptives in other ways).</p>
<p>When we compare 4.35 to the neutral point of 4, the resulting t value is 8.53. With degrees of freedom 342, the p value is very small, at 0.000000000000000477477. Because p value is smaller than the alpha level of .05, the result is statistically significant. Because 4.35 is statistically significantly greater than 4, we would conclude that there is sufficient evidence that the satisfaction with life scores in 2019 is greater than the neutral value of 4.</p>
<p>In addition, the 95% confidence interval is [4.27, 4.43], which is interpreted as follows: We are 95% confident that the true 2019 satisfaction with life score is between 4.27 and 4.43.</p>
<p>You can code the same thing using <code>t.test()</code> in a slightly different way, known as the formula interface:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="hypotest.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(swls2019_avg <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">4</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<p>You’ll get the same result!</p>
</div>
<div id="effect-size-cohens-d" class="section level3 hasAnchor" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> Effect Size: Cohen’s d<a href="hypotest.html#effect-size-cohens-d" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In addition to hypothesis testing, we also need to look at (standardised) effect size. Effect sizes tell you how large the effect (or the difference) is. The effect size we usually calculate for t tests is the Cohen’s d, where d = 0.2 is a small effect size, d = 0.5 is a medium effect size, and d = 0.8 is a large effect size.</p>
<p>We can calculate Cohen’s d using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="hypotest.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb84-2"><a href="hypotest.html#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb84-3"><a href="hypotest.html#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="hypotest.html#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen&#39;s d, with mu = 4</span></span>
<span id="cb84-5"><a href="hypotest.html#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(swls2019_avg <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data, <span class="at">mu =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
## 0.46      | [0.35, 0.57]
## 
## - Deviation from a difference of 4.</code></pre>
<p>Given the Cohen’s d is 0.46, we can consider this a small to medium effect size.</p>
</div>
</div>
<div id="correlated-groups-t-test" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Correlated Groups T Test<a href="hypotest.html#correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="when-to-use-a-correlated-groups-t-test" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> When to Use A Correlated Groups T Test<a href="hypotest.html#when-to-use-a-correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use a correlated groups t test when we want to compare two sets of data to see if they are different from each other. Importantly, the two sets of data are paired in some way (e.g., they come from the same person).</p>
<p>Suppose we want to know from our hypothetical dataset whether people’s satisfaction with life scores changed from 2019 to 2021. We have (or can calculate) the same individuals’ satisfaction with life scores in 2019 and in 2021. Given the same individual provided the 2019 and the 2021 scores, the two sets of scores are considered paired or correlated.</p>
<p>To find out whether there is a difference between these two sets of (paired) scores, we can therefore conduct a correlated groups t test.</p>
</div>
<div id="conducting-and-interpreting-the-correlated-groups-t-test" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Conducting and Interpreting the Correlated Groups T Test<a href="hypotest.html#conducting-and-interpreting-the-correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Again, before conducting the correlated groups t test, remember to get the descriptive statistics for each set of scores.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="hypotest.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average satisfaction with life score in 2021 for each participant. </span></span>
<span id="cb86-2"><a href="hypotest.html#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="co"># If you did not calculate the average satisfaction with life score in 2019 earlier, you will want to do that before continuing.</span></span>
<span id="cb86-3"><a href="hypotest.html#cb86-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb86-4"><a href="hypotest.html#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swls2021_avg =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(swls2021_1<span class="sc">:</span>swls2021_5))))</span>
<span id="cb86-5"><a href="hypotest.html#cb86-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-6"><a href="hypotest.html#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the descriptives</span></span>
<span id="cb86-7"><a href="hypotest.html#cb86-7" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(data<span class="sc">$</span>swls2019_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 4.35 0.77    4.4    4.33 0.89   2   6     4  0.1    -0.48 0.04</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="hypotest.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(data<span class="sc">$</span>swls2021_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 3.85 0.67    3.8    3.84 0.89   2 5.8   3.8  0.1    -0.37 0.04</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="hypotest.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the correlated groups t test to compare the satisfaction with life scores in 2019  and in 2021 to see if there is any change over the two years. </span></span>
<span id="cb90-2"><a href="hypotest.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="co"># x = data$swls2019_avg tells R what the first set of scores is</span></span>
<span id="cb90-3"><a href="hypotest.html#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="co"># y = data$swls2021_avg tells R what the second set of scores is</span></span>
<span id="cb90-4"><a href="hypotest.html#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># &quot;two-sided&quot; means we&#39;re conducting a two-tailed test</span></span>
<span id="cb90-5"><a href="hypotest.html#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="co"># mu = 0 means we&#39;re comparing the difference between the 2019 and 2021 scores against the value of 0</span></span>
<span id="cb90-6"><a href="hypotest.html#cb90-6" aria-hidden="true" tabindex="-1"></a><span class="co"># paired = TRUE means that each individual offered pairs of observations (i.e., swls2019_avg and swls2021_avg)</span></span>
<span id="cb90-7"><a href="hypotest.html#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="co"># conf.level = 0.95 means we want the 95% confidence level </span></span>
<span id="cb90-8"><a href="hypotest.html#cb90-8" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> data<span class="sc">$</span>swls2019_avg, <span class="at">y =</span> data<span class="sc">$</span>swls2021_avg, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  data$swls2019_avg and data$swls2021_avg
## t = 27.82957, df = 342, p-value &lt; 0.000000000000000222
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.46493219 0.53565090
## sample estimates:
## mean difference 
##     0.500291545</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="hypotest.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> data<span class="sc">$</span>swls2019_avg, <span class="at">y =</span> data<span class="sc">$</span>swls2021_avg, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  data$swls2019_avg and data$swls2021_avg
## t = 9.074279, df = 672.8316, p-value &lt; 0.000000000000000222
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.392038268 0.608544823
## sample estimates:
##  mean of x  mean of y 
## 4.35335277 3.85306122</code></pre>
<p>The results indicate that the average of the difference between swls2019_avg and swls2021_avg is 0.50. When we compare this difference against 0, the resulting t value is 27.83. With degrees of freedom 342, the p value is very small, at 0.000000000000000222. Because p value is smaller than the alpha level of .05, the result is statistically significant. Because 4.35 (mean for 2019) is statistically significantly greater than 3.85 (mean for 2021), we would conclude that there is sufficient evidence that on average, the satisfaction with life scores in 2019 is greater than the satisfaction with life scores in 2021.</p>
<p>The 95% confidence interval is [0.46, 0.54] is interpreted as follows: We are 95% confident that the true difference between the 2019 and 2021 satisfaction with life scores is between 0.46 and 0.54.</p>
<p>Similar to the one-sample t test, the correlated groups t test also has a formula interface:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="hypotest.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="fu">Pair</span>(swls2019_avg, swls2021_avg) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb94-2"><a href="hypotest.html#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="hypotest.html#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice that the paired = TRUE argument has been taken out because it&#39;s been replaced by Pair(swls2019_avg, swls2021_avg).</span></span></code></pre></div>
<p>You’ll get the same result!</p>
</div>
<div id="effect-size-cohens-d-1" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> Effect Size: Cohen’s d<a href="hypotest.html#effect-size-cohens-d-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we need to get the effect size, Cohen’s d, for correlated groups t test using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="hypotest.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen&#39;s d, with mu = 0 (which is the default, so no need to state)</span></span>
<span id="cb95-2"><a href="hypotest.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(<span class="fu">Pair</span>(swls2019_avg, swls2021_avg) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
## 1.50      | [1.35, 1.66]</code></pre>
<p>Given the Cohen’s d is 1.50, we can consider this a large effect size. In other words, there is a large difference between the 2019 and 2021 satisfaction with life scores.</p>
</div>
</div>
<div id="independent-groups-t-test" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Independent Groups T Test<a href="hypotest.html#independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="when-to-use-an-independent-groups-t-test" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> When to Use An Independent Groups T Test<a href="hypotest.html#when-to-use-an-independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use an independent groups t test when we want to compare two sets of data to see if they are different from each other. Importantly, the two sets of data are independent (i.e., they are NOT paired).</p>
<p>Suppose we want to know whether men and women differ in satisfaction with life in 2019. In other words, we’re comparing the satisfaction with life scores for the group of men with that for the group of women. In this case, because the men and women are not paired with each other in any way, we consider the two sets of satisfaction with life scores as independent.</p>
<p>Therefore, to answer our research question, we will conduct an independent groups t test.</p>
</div>
<div id="conducting-and-interpreting-the-independent-groups-t-test" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> Conducting and Interpreting the Independent Groups T Test<a href="hypotest.html#conducting-and-interpreting-the-independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As usual, before conducting the independent groups t test, we will get the descriptive statistics for each group.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="hypotest.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, we need to convert gender into a factor </span></span>
<span id="cb97-2"><a href="hypotest.html#cb97-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>gender, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>))</span>
<span id="cb97-3"><a href="hypotest.html#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="hypotest.html#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Next, we get the descriptive statistics for each group, male and female</span></span>
<span id="cb97-5"><a href="hypotest.html#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(data<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> data<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: male
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 168 4.08 0.61    4.2    4.06 0.59   3 5.8   2.8 0.26    -0.46 0.05
## ------------------------------------------------------------ 
## group: female
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 175 4.62 0.81    4.6    4.65 0.89   2   6     4 -0.35    -0.25 0.06</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="hypotest.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then, we conduct the independent groups t test</span></span>
<span id="cb99-2"><a href="hypotest.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice that this t.test code takes the form of the formula interface: DV ~ IV</span></span>
<span id="cb99-3"><a href="hypotest.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="co"># &quot;two-sided&quot; tells R we&#39;re conducting a two-tailed test</span></span>
<span id="cb99-4"><a href="hypotest.html#cb99-4" aria-hidden="true" tabindex="-1"></a><span class="co"># mu = 0 means we&#39;re comparing the difference between males and females against the value of 0</span></span>
<span id="cb99-5"><a href="hypotest.html#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># var.equal = TRUE means that we&#39;re assuming homogeneity of variance is met (if homogeneity of variance is violated, use var.equal = FALSE and R will conduct Welch corrections)</span></span>
<span id="cb99-6"><a href="hypotest.html#cb99-6" aria-hidden="true" tabindex="-1"></a><span class="co"># conf.level = 0.95 means we want the 95% confidence level</span></span>
<span id="cb99-7"><a href="hypotest.html#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>swls2019_avg <span class="sc">~</span> data<span class="sc">$</span>gender, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>), <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  data$swls2019_avg by data$gender
## t = -6.898557, df = 341, p-value = 0.0000000000256373
## alternative hypothesis: true difference in means between group male and group female is not equal to 0
## 95 percent confidence interval:
##  -0.689132523 -0.383343668
## sample estimates:
##   mean in group male mean in group female 
##            4.0797619            4.6160000</code></pre>
<p>The results indicate that the average satisfaction with life score for those who identify as male is 4.08 and 4.62 for those who identify as female. When we compare the difference between the two genders against 0, the resulting t value is -6.90. With degrees of freedom 341, the p value is very small, at 0.0000000000256373. Because p value is smaller than the alpha level of .05, the result is statistically significant. Because 4.62 is statistically significantly greater than 4.08, we would conclude that there is sufficient evidence that the satisfaction with life scores in 2019 is greater for females than for males.</p>
<p>The 95% confidence interval is [-0.69, -0.38] which is interpreted as follows: We are 95% confident that the true difference in 2019 satisfaction with life score between males and females is between -0.69 and -0.38.</p>
<p><em>Note.</em> In calculating the t statistic, R took male - female (since 0 = male and 1 = female, and R takes the group with the smaller number and subtracts the group with the larger number) . Because males have a smaller 2019 SWLS than females, the t statistic is negative. However, if R had taken female - male, the t statistic would be positive. Whether it is positive or negative doesn’t matter so long as you know which group has a higher mean and therefore can interpret correctly the direction of the effect.</p>
</div>
<div id="effect-size-cohens-d-2" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> Effect Size: Cohen’s d<a href="hypotest.html#effect-size-cohens-d-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we need to get the effect size, Cohen’s d, for the independent groups t test using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="hypotest.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen&#39;s d, with mu = 0 (which is the default, so no need to state)</span></span>
<span id="cb101-2"><a href="hypotest.html#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(swls2019_avg <span class="sc">~</span> gender, <span class="at">data =</span> data)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |         95% CI
## --------------------------
## -0.75     | [-0.96, -0.53]
## 
## - Estimated using pooled SD.</code></pre>
<p>Given the Cohen’s d is -0.75, we can consider this a medium-large effect size.</p>
<p><em>Note.</em> There is a negative sign here because R took <code>male - female</code>. If R took <code>female - male</code>, Cohen’s d will be positive.</p>
</div>
</div>
<div id="one-way-between-subjects-anova" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> One-Way Between-Subjects ANOVA<a href="hypotest.html#one-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The independent groups t test is used when you want to compare the scores between two independent groups. But what if you have more than two independent groups? You would use the one-way between-subjects ANOVA.</p>
<p>So, suppose we want to know whether people with different marital status report differing levels of satisfaction with life scores. In other words, we might want to find out whether there is at least one mean difference between: a) married vs divorced, b) married vs widowed, c) divorced vs widowed.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="hypotest.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert marital status into factor</span></span>
<span id="cb103-2"><a href="hypotest.html#cb103-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>marital_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>marital_status, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;married&quot;</span>, <span class="st">&quot;divorced&quot;</span>, <span class="st">&quot;widowed&quot;</span>))</span>
<span id="cb103-3"><a href="hypotest.html#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="hypotest.html#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive statistics</span></span>
<span id="cb103-5"><a href="hypotest.html#cb103-5" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(data<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> data<span class="sc">$</span>marital_status)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: married
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 118 4.58 0.85    4.5     4.6 1.19   3   6     3 -0.01    -1.08 0.08
## ------------------------------------------------------------ 
## group: divorced
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 114 4.16 0.72    4.3    4.16 0.74   2 5.6   3.6 -0.17     -0.1 0.07
## ------------------------------------------------------------ 
## group: widowed
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 111  4.3 0.65    4.4    4.27 0.59 3.2   6   2.8 0.18    -0.74 0.06</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="hypotest.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the ANOVA</span></span>
<span id="cb105-2"><a href="hypotest.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA is strange in that to view the results, you need to save it as an object first. </span></span>
<span id="cb105-3"><a href="hypotest.html#cb105-3" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">aov</span>(swls2019_avg <span class="sc">~</span> marital_status, <span class="at">data =</span> data)  </span>
<span id="cb105-4"><a href="hypotest.html#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="hypotest.html#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the summary results</span></span>
<span id="cb105-6"><a href="hypotest.html#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code></pre></div>
<pre><code>##                 Df   Sum Sq Mean Sq F value      Pr(&gt;F)    
## marital_status   2  10.7832 5.39159 9.62428 0.000085953 ***
## Residuals      340 190.4705 0.56021                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There are two other ways to run the ANOVA. The results will be exactly the same.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="hypotest.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative 1</span></span>
<span id="cb107-2"><a href="hypotest.html#cb107-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">aov</span>(data<span class="sc">$</span>swls2019_avg <span class="sc">~</span> data<span class="sc">$</span>marital_status)</span>
<span id="cb107-3"><a href="hypotest.html#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="hypotest.html#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Alternative 2</span></span>
<span id="cb107-5"><a href="hypotest.html#cb107-5" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> data, swls2019_avg <span class="sc">~</span> marital_status)</span></code></pre></div>
<p>Because the ANOVA results are statistically significant, we might want to follow up with pairwise comparisons (Tukey’s HSD). To run this, we need the <code>DescTools</code> package. (Remember to install the package Before continuing.)</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="hypotest.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb108-2"><a href="hypotest.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb108-3"><a href="hypotest.html#cb108-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-4"><a href="hypotest.html#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a posthoc test on the results using Tukey&#39;s HSD. Oh, and give me the 95% CI.</span></span>
<span id="cb108-5"><a href="hypotest.html#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="fu">PostHocTest</span>(results, <span class="at">method =</span> <span class="st">&quot;hsd&quot;</span>, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>## 
##   Posthoc multiple comparisons of means : Tukey HSD 
##     95% family-wise confidence level
## 
## $marital_status
##                          diff        lwr.ci        upr.ci     pval    
## divorced-married -0.423342254 -0.6547275679 -0.1919569400 0.000064 ***
## widowed-married  -0.280241258 -0.5132115136 -0.0472710028   0.0136 *  
## widowed-divorced  0.143100996 -0.0918420376  0.3780440291   0.3247    
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>If you want other posthoc tests, you can change the <code>method</code> portion. Type <code>?PostHocTest</code> into the console to find out more about the different post hoc tests available to you.</p>
</div>
<div id="two-way-between-subjects-anova" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Two-Way Between-Subjects ANOVA<a href="hypotest.html#two-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose you want to know whether the difference in satisfaction with life scores between male and female depends on whether they have children. To find out, you will need to conduct a two-way between-subjects ANOVA.</p>
<p>You’ll need the <code>car</code> package to run the ANOVA.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="hypotest.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb110-2"><a href="hypotest.html#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb110-3"><a href="hypotest.html#cb110-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-4"><a href="hypotest.html#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Change have_children into a factor</span></span>
<span id="cb110-5"><a href="hypotest.html#cb110-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>have_children <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>have_children, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;no children&quot;</span>, <span class="st">&quot;have children&quot;</span>))</span>
<span id="cb110-6"><a href="hypotest.html#cb110-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-7"><a href="hypotest.html#cb110-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Change contrasts settings when estimating Type-3 sum of squares</span></span>
<span id="cb110-8"><a href="hypotest.html#cb110-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&#39;contr.sum&#39;</span>, <span class="st">&#39;contr.poly&#39;</span>))</span>
<span id="cb110-9"><a href="hypotest.html#cb110-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-10"><a href="hypotest.html#cb110-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the model being tested and store the model to [mod1]</span></span>
<span id="cb110-11"><a href="hypotest.html#cb110-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The model has the following format: DV ~ IV1 + IV2 + IV1*IV2</span></span>
<span id="cb110-12"><a href="hypotest.html#cb110-12" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(swls2019_avg <span class="sc">~</span> gender <span class="sc">+</span> have_children <span class="sc">+</span> gender<span class="sc">*</span>have_children, <span class="at">data =</span> data)  </span>
<span id="cb110-13"><a href="hypotest.html#cb110-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-14"><a href="hypotest.html#cb110-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct Two-Way ANOVA and get the ANOVA summary table</span></span>
<span id="cb110-15"><a href="hypotest.html#cb110-15" aria-hidden="true" tabindex="-1"></a><span class="co"># type = &quot;3&quot; refers to Type 3 sum of squares. For this class, we will use Type 3 sum of squares.</span></span>
<span id="cb110-16"><a href="hypotest.html#cb110-16" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod1, <span class="at">type =</span> <span class="st">&quot;3&quot;</span>)   </span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: swls2019_avg
##                        Sum Sq  Df     F value                 Pr(&gt;F)    
## (Intercept)          6366.863   1 13955.51399 &lt; 0.000000000000000222 ***
## gender                 19.801   1    43.40250       0.00000000017028 ***
## have_children          18.578   1    40.72079       0.00000000057671 ***
## gender:have_children    3.093   1     6.77873              0.0096307 ** 
## Residuals             154.660 339                                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Because the interaction is statistically significant, we will conduct the simple effects analysis. This is essentially like conducting independent groups t tests (with some corrections). Since we want to find out whether the difference between male and female’s satisfaction with life scores depends on having children, the two tests we will conduct would be: 1) difference in the satisfaction with life scores of males and females who have children; 2) difference in the satisfaction with life scores of males and females who do not have children.</p>
<p>To do the simple effects analyses, we need the <code>emmeans</code> package.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="hypotest.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb112-2"><a href="hypotest.html#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb112-3"><a href="hypotest.html#cb112-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-4"><a href="hypotest.html#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="co"># first, let&#39;s look at a plot</span></span>
<span id="cb112-5"><a href="hypotest.html#cb112-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate Lines: have_children, X axis: gender</span></span>
<span id="cb112-6"><a href="hypotest.html#cb112-6" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(mod1, have_children <span class="sc">~</span> gender)</span></code></pre></div>
<p><img src="PSYC208_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="hypotest.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Next, we conduct the simple effects investigating 1) the effect of gender (difference between males and females) for those who have children, and 2) the effect of gender for those who do not have children.  </span></span>
<span id="cb113-2"><a href="hypotest.html#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod1, pairwise <span class="sc">~</span> gender <span class="sc">|</span> have_children)  <span class="co"># comparing the pair of conditions in gender for each level of have_children</span></span></code></pre></div>
<pre><code>## $emmeans
## have_children = no children:
##  gender emmean     SE  df lower.CL upper.CL
##  male     3.95 0.0704 339     3.82     4.09
##  female   4.25 0.0770 339     4.10     4.40
## 
## have_children = have children:
##  gender emmean     SE  df lower.CL upper.CL
##  male     4.23 0.0775 339     4.08     4.38
##  female   4.91 0.0682 339     4.77     5.04
## 
## Confidence level used: 0.95 
## 
## $contrasts
## have_children = no children:
##  contrast      estimate    SE  df t.ratio p.value
##  male - female   -0.292 0.104 339  -2.803  0.0054
## 
## have_children = have children:
##  contrast      estimate    SE  df t.ratio p.value
##  male - female   -0.675 0.103 339  -6.534  &lt;.0001</code></pre>
<p>Suppose, though, you were interested in looking at the effect of having children by gender. In other words, you’re interested in looking at the difference 1) between men with and men without children, and 2) between women with and women without children. In this case, you will swap the variables around.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="hypotest.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, let&#39;s look at a plot</span></span>
<span id="cb115-2"><a href="hypotest.html#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate Lines: gender, X axis: have_children</span></span>
<span id="cb115-3"><a href="hypotest.html#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(mod1, gender <span class="sc">~</span> have_children)</span></code></pre></div>
<p><img src="PSYC208_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="hypotest.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Next, we conduct the simple effects investigating 1) the effect of having children (difference between having children and not having children) for males, and 2) of having children (difference between having children and not having children) for females.  </span></span>
<span id="cb116-2"><a href="hypotest.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod1, pairwise <span class="sc">~</span> have_children <span class="sc">|</span> gender)  <span class="co"># comparing the pair of conditions in have_children for each level of gender</span></span></code></pre></div>
<pre><code>## $emmeans
## gender = male:
##  have_children emmean     SE  df lower.CL upper.CL
##  no children     3.95 0.0704 339     3.82     4.09
##  have children   4.23 0.0775 339     4.08     4.38
## 
## gender = female:
##  have_children emmean     SE  df lower.CL upper.CL
##  no children     4.25 0.0770 339     4.10     4.40
##  have children   4.91 0.0682 339     4.77     5.04
## 
## Confidence level used: 0.95 
## 
## $contrasts
## gender = male:
##  contrast                    estimate    SE  df t.ratio p.value
##  no children - have children   -0.277 0.105 339  -2.648  0.0085
## 
## gender = female:
##  contrast                    estimate    SE  df t.ratio p.value
##  no children - have children   -0.659 0.103 339  -6.410  &lt;.0001</code></pre>
</div>
<div id="correlation" class="section level2 hasAnchor" number="8.9">
<h2><span class="header-section-number">8.9</span> Correlation<a href="hypotest.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose you want to find out whether people who have higher satisfaction with life scores in 2019 also have higher satisfaction with life scores in 2021. Here is where you will conduct a correlation.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="hypotest.html#cb118-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb118-2"><a href="hypotest.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swls2021_avg =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(swls2021_1<span class="sc">:</span>swls2021_5))))</span>
<span id="cb118-3"><a href="hypotest.html#cb118-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-4"><a href="hypotest.html#cb118-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>swls2019_avg, data<span class="sc">$</span>swls2021_avg)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data$swls2019_avg and data$swls2021_avg
## t = 38.39589, df = 341, p-value &lt; 0.000000000000000222
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.879200201 0.919351528
## sample estimates:
##         cor 
## 0.901191727</code></pre>
<p>Alternatively, you can do the correlation test this way:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="hypotest.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative 1</span></span>
<span id="cb120-2"><a href="hypotest.html#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="sc">~</span> swls2019_avg <span class="sc">+</span> swls2021_avg, </span>
<span id="cb120-3"><a href="hypotest.html#cb120-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> data)</span>
<span id="cb120-4"><a href="hypotest.html#cb120-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-5"><a href="hypotest.html#cb120-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative 2</span></span>
<span id="cb120-6"><a href="hypotest.html#cb120-6" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb120-7"><a href="hypotest.html#cb120-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor.test</span>(<span class="at">formula =</span> <span class="sc">~</span> swls2019_avg <span class="sc">+</span> swls2021_avg, .)</span></code></pre></div>
<p>All ways would give you the same result.</p>
</div>
<div id="regression" class="section level2 hasAnchor" number="8.10">
<h2><span class="header-section-number">8.10</span> Regression<a href="hypotest.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose you want to predict <code>swls2021_avg</code> from <code>swls2019_avg</code>. Here, we might want to conduct linear regression.</p>
<p>The simplest form of linear regression is called simple linear regression. It only has two variables: one predictor and one outcome.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="hypotest.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct regression</span></span>
<span id="cb121-2"><a href="hypotest.html#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the model takes the form of Y ~ X (where Y = outcome, X = predictor)</span></span>
<span id="cb121-3"><a href="hypotest.html#cb121-3" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb121-4"><a href="hypotest.html#cb121-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(swls2021_avg <span class="sc">~</span> swls2019_avg, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> </span>
<span id="cb121-5"><a href="hypotest.html#cb121-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(.)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = swls2021_avg ~ swls2019_avg, data = .)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -1.056645 -0.248328 -0.006664  0.193336  0.801654 
## 
## Coefficients:
##               Estimate Std. Error  t value               Pr(&gt;|t|)    
## (Intercept)  0.4065882  0.0911404  4.46112            0.000011087 ***
## swls2019_avg 0.7916825  0.0206189 38.39589 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.292508 on 341 degrees of freedom
## Multiple R-squared:  0.812147,   Adjusted R-squared:  0.811596 
## F-statistic: 1474.24 on 1 and 341 DF,  p-value: &lt; 0.000000000000000222</code></pre>
<p>Unfortunately, the summary doesn’t give us the confidence interval. To get that, we need to specify that we want the confidence interval with the <code>confint()</code> function.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="hypotest.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To get the 95% confidence interval</span></span>
<span id="cb123-2"><a href="hypotest.html#cb123-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb123-3"><a href="hypotest.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(swls2021_avg <span class="sc">~</span> swls2019_avg, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> </span>
<span id="cb123-4"><a href="hypotest.html#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">confint</span>(.)</span></code></pre></div>
<pre><code>##                    2.5 %      97.5 %
## (Intercept)  0.227320000 0.585856416
## swls2019_avg 0.751126141 0.832238772</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tha3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tha4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/hueywoon/assignment/blob/master/07-hypotesting.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
