<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Hypothesis Testing | PSYC208 R Companion Website</title>
  <meta name="description" content="This is the companion website to my PSYC208 class." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Hypothesis Testing | PSYC208 R Companion Website" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the companion website to my PSYC208 class." />
  <meta name="github-repo" content="hueywoon/assignment" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Hypothesis Testing | PSYC208 R Companion Website" />
  
  <meta name="twitter:description" content="This is the companion website to my PSYC208 class." />
  

<meta name="author" content="Huey Woon LEE" />


<meta name="date" content="2025-01-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="section-tha3.html"/>

<!-- HEAD_CONTENT -->


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC208 R Companion Website</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About This Website</a></li>
<li class="chapter" data-level="1" data-path="section-start.html"><a href="section-start.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="section-start.html"><a href="section-start.html#section-install-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="section-start.html"><a href="section-start.html#section-the-rstudio-interface"><i class="fa fa-check"></i><b>1.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="1.3" data-path="section-start.html"><a href="section-start.html#section-r-script"><i class="fa fa-check"></i><b>1.3</b> R Script</a></li>
<li class="chapter" data-level="1.4" data-path="section-start.html"><a href="section-start.html#section-some-tips-and-tricks"><i class="fa fa-check"></i><b>1.4</b> Some Tips and Tricks</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="section-start.html"><a href="section-start.html#section-softwrap-long-lines"><i class="fa fa-check"></i><b>1.4.1</b> Softwrap Long Lines</a></li>
<li class="chapter" data-level="1.4.2" data-path="section-start.html"><a href="section-start.html#section-make-notes-or-comments"><i class="fa fa-check"></i><b>1.4.2</b> Make Notes or Comments</a></li>
<li class="chapter" data-level="1.4.3" data-path="section-start.html"><a href="section-start.html#section-multi-line-comments"><i class="fa fa-check"></i><b>1.4.3</b> Multi-Line Comments</a></li>
<li class="chapter" data-level="1.4.4" data-path="section-start.html"><a href="section-start.html#section-style-guide"><i class="fa fa-check"></i><b>1.4.4</b> Style Guide</a></li>
<li class="chapter" data-level="1.4.5" data-path="section-start.html"><a href="section-start.html#section-setting-working-directory"><i class="fa fa-check"></i><b>1.4.5</b> Setting Working Directory</a></li>
<li class="chapter" data-level="1.4.6" data-path="section-start.html"><a href="section-start.html#section-using-r-projects"><i class="fa fa-check"></i><b>1.4.6</b> Using R Projects</a></li>
<li class="chapter" data-level="1.4.7" data-path="section-start.html"><a href="section-start.html#section-compile-report"><i class="fa fa-check"></i><b>1.4.7</b> Compile Report</a></li>
<li class="chapter" data-level="1.4.8" data-path="section-start.html"><a href="section-start.html#section-debugging"><i class="fa fa-check"></i><b>1.4.8</b> Debugging</a></li>
<li class="chapter" data-level="1.4.9" data-path="section-start.html"><a href="section-start.html#section-last-words"><i class="fa fa-check"></i><b>1.4.9</b> Last Words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="section-basics.html"><a href="section-basics.html"><i class="fa fa-check"></i><b>2</b> Basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="section-basics.html"><a href="section-basics.html#section-some-basic-commands"><i class="fa fa-check"></i><b>2.1</b> Some Basic Commands</a></li>
<li class="chapter" data-level="2.2" data-path="section-basics.html"><a href="section-basics.html#section-typing-and-executing-commands"><i class="fa fa-check"></i><b>2.2</b> Typing and Executing Commands</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="section-basics.html"><a href="section-basics.html#section-exercise"><i class="fa fa-check"></i><b>2.2.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="section-basics.html"><a href="section-basics.html#section-entering-data-directly-into-r"><i class="fa fa-check"></i><b>2.3</b> Entering Data Directly Into R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="section-tha1.html"><a href="section-tha1.html"><i class="fa fa-check"></i><b>3</b> Test Yourselves 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="section-tha1.html"><a href="section-tha1.html#section-instructions"><i class="fa fa-check"></i><b>3.1</b> Instructions</a></li>
<li class="chapter" data-level="3.2" data-path="section-tha1.html"><a href="section-tha1.html#section-data"><i class="fa fa-check"></i><b>3.2</b> Data</a></li>
<li class="chapter" data-level="3.3" data-path="section-tha1.html"><a href="section-tha1.html#section-suggested-answers"><i class="fa fa-check"></i><b>3.3</b> Suggested Answers</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="section-tidyverse.html"><a href="section-tidyverse.html"><i class="fa fa-check"></i><b>4</b> Using tidyverse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-installing-and-loading-tidyverse"><i class="fa fa-check"></i><b>4.1</b> Installing and Loading tidyverse</a></li>
<li class="chapter" data-level="4.2" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-import-data"><i class="fa fa-check"></i><b>4.2</b> Import Data</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-swb-dataset"><i class="fa fa-check"></i><b>4.2.1</b> SWB Dataset</a></li>
<li class="chapter" data-level="4.2.2" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-check-imported-dataset"><i class="fa fa-check"></i><b>4.2.2</b> Check Imported Dataset</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-factors"><i class="fa fa-check"></i><b>4.3</b> Factors</a></li>
<li class="chapter" data-level="4.4" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>4.4</b> Data Wrangling With dplyr</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-select"><i class="fa fa-check"></i><b>4.4.1</b> Select()</a></li>
<li class="chapter" data-level="4.4.2" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-filter"><i class="fa fa-check"></i><b>4.4.2</b> Filter()</a></li>
<li class="chapter" data-level="4.4.3" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-mutate"><i class="fa fa-check"></i><b>4.4.3</b> Mutate()</a></li>
<li class="chapter" data-level="4.4.4" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-summarise"><i class="fa fa-check"></i><b>4.4.4</b> Summarise()</a></li>
<li class="chapter" data-level="4.4.5" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-group_by"><i class="fa fa-check"></i><b>4.4.5</b> Group_by()</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-tables-and-plots-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Tables and Plots with ggplot2</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-frequency-tables"><i class="fa fa-check"></i><b>4.5.1</b> Frequency Tables</a></li>
<li class="chapter" data-level="4.5.2" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-bar-plots-with-ggplot2"><i class="fa fa-check"></i><b>4.5.2</b> Bar Plots with ggplot2</a></li>
<li class="chapter" data-level="4.5.3" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-histograms-with-ggplot2"><i class="fa fa-check"></i><b>4.5.3</b> Histograms with ggplot2</a></li>
<li class="chapter" data-level="4.5.4" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-scatterplot-with-ggplot2"><i class="fa fa-check"></i><b>4.5.4</b> Scatterplot with ggplot2</a></li>
<li class="chapter" data-level="4.5.5" data-path="section-tidyverse.html"><a href="section-tidyverse.html#section-last-words-1"><i class="fa fa-check"></i><b>4.5.5</b> Last Words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="section-tha2.html"><a href="section-tha2.html"><i class="fa fa-check"></i><b>5</b> Test Yourselves 2</a>
<ul>
<li class="chapter" data-level="5.1" data-path="section-tha2.html"><a href="section-tha2.html#section-instructions-1"><i class="fa fa-check"></i><b>5.1</b> Instructions</a></li>
<li class="chapter" data-level="5.2" data-path="section-tha2.html"><a href="section-tha2.html#section-legend"><i class="fa fa-check"></i><b>5.2</b> Legend</a></li>
<li class="chapter" data-level="5.3" data-path="section-tha2.html"><a href="section-tha2.html#section-suggested-answers-1"><i class="fa fa-check"></i><b>5.3</b> Suggested Answers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="section-scale.html"><a href="section-scale.html"><i class="fa fa-check"></i><b>6</b> Multi-Item Measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="section-scale.html"><a href="section-scale.html#section-overview"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="section-scale.html"><a href="section-scale.html#section-dataset"><i class="fa fa-check"></i><b>6.2</b> Dataset</a></li>
<li class="chapter" data-level="6.3" data-path="section-scale.html"><a href="section-scale.html#section-check-the-pattern-of-responses-correlation-coefficient"><i class="fa fa-check"></i><b>6.3</b> Check the Pattern of Responses: Correlation Coefficient</a></li>
<li class="chapter" data-level="6.4" data-path="section-scale.html"><a href="section-scale.html#section-reliability-analysis-cronbachs-alpha"><i class="fa fa-check"></i><b>6.4</b> Reliability Analysis: Cronbach’s Alpha</a></li>
<li class="chapter" data-level="6.5" data-path="section-scale.html"><a href="section-scale.html#section-compute-the-average-score-for-the-scale"><i class="fa fa-check"></i><b>6.5</b> Compute the average score for the scale</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="section-tha3.html"><a href="section-tha3.html"><i class="fa fa-check"></i><b>7</b> Test Yourselves 3</a>
<ul>
<li class="chapter" data-level="7.1" data-path="section-tha3.html"><a href="section-tha3.html#section-instructions-2"><i class="fa fa-check"></i><b>7.1</b> Instructions</a></li>
<li class="chapter" data-level="7.2" data-path="section-tha3.html"><a href="section-tha3.html#section-legend-1"><i class="fa fa-check"></i><b>7.2</b> Legend</a></li>
<li class="chapter" data-level="7.3" data-path="section-tha3.html"><a href="section-tha3.html#section-suggested-answers-2"><i class="fa fa-check"></i><b>7.3</b> Suggested Answers</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="section-hypotest.html"><a href="section-hypotest.html"><i class="fa fa-check"></i><b>8</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-overview-1"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-load-packages-and-dataset"><i class="fa fa-check"></i><b>8.2</b> Load Packages and Dataset</a></li>
<li class="chapter" data-level="8.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-scientific-notation"><i class="fa fa-check"></i><b>8.3</b> Scientific Notation</a></li>
<li class="chapter" data-level="8.4" data-path="section-hypotest.html"><a href="section-hypotest.html#section-one-sample-t-test"><i class="fa fa-check"></i><b>8.4</b> One-Sample T Test</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-one-sample-t-test"><i class="fa fa-check"></i><b>8.4.1</b> When to Use A One-Sample T Test</a></li>
<li class="chapter" data-level="8.4.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-one-sample-t-test"><i class="fa fa-check"></i><b>8.4.2</b> Conducting and Interpreting the One-Sample T Test</a></li>
<li class="chapter" data-level="8.4.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-cohens-d"><i class="fa fa-check"></i><b>8.4.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="section-hypotest.html"><a href="section-hypotest.html#section-correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5</b> Correlated Groups T test</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5.1</b> When to Use A Correlated Groups T Test</a></li>
<li class="chapter" data-level="8.5.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-correlated-groups-t-test"><i class="fa fa-check"></i><b>8.5.2</b> Conducting and Interpreting the Correlated Groups T Test</a></li>
<li class="chapter" data-level="8.5.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-cohens-d-1"><i class="fa fa-check"></i><b>8.5.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="section-hypotest.html"><a href="section-hypotest.html#section-independent-groups-t-test"><i class="fa fa-check"></i><b>8.6</b> Independent Groups T Test</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-an-independent-groups-t-test"><i class="fa fa-check"></i><b>8.6.1</b> When to Use An Independent Groups T Test</a></li>
<li class="chapter" data-level="8.6.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-independent-groups-t-test"><i class="fa fa-check"></i><b>8.6.2</b> Conducting and Interpreting the Independent Groups T Test</a></li>
<li class="chapter" data-level="8.6.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-cohens-d-2"><i class="fa fa-check"></i><b>8.6.3</b> Effect Size: Cohen’s d</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="section-hypotest.html"><a href="section-hypotest.html#section-one-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.7</b> One-Way Between-Subjects ANOVA</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-one-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.7.1</b> When to Use A One-Way Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="8.7.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-one-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.7.2</b> Conducting and Interpreting the One-Way Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="8.7.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-posthoc-analysis-tukeys-hsd"><i class="fa fa-check"></i><b>8.7.3</b> Posthoc Analysis: Tukey’s HSD</a></li>
<li class="chapter" data-level="8.7.4" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-eta-squared"><i class="fa fa-check"></i><b>8.7.4</b> Effect Size: Eta-Squared</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="section-hypotest.html"><a href="section-hypotest.html#section-two-way-between-subjects-factorial-anova"><i class="fa fa-check"></i><b>8.8</b> Two-Way Between-Subjects Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-two-way-between-subjects-factorial-anova"><i class="fa fa-check"></i><b>8.8.1</b> When to Use A Two-Way Between-Subjects Factorial ANOVA</a></li>
<li class="chapter" data-level="8.8.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-two-way-between-subjects-anova"><i class="fa fa-check"></i><b>8.8.2</b> Conducting and Interpreting the Two-Way Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="8.8.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-simple-effects-analysis"><i class="fa fa-check"></i><b>8.8.3</b> Conducting and Interpreting the Simple Effects Analysis</a></li>
<li class="chapter" data-level="8.8.4" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-partial-eta-squared"><i class="fa fa-check"></i><b>8.8.4</b> Effect Size: Partial Eta-Squared</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="section-hypotest.html"><a href="section-hypotest.html#section-correlation"><i class="fa fa-check"></i><b>8.9</b> Correlation</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-correlation"><i class="fa fa-check"></i><b>8.9.1</b> When to Use A Correlation</a></li>
<li class="chapter" data-level="8.9.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-correlation"><i class="fa fa-check"></i><b>8.9.2</b> Conducting and Interpreting the Correlation</a></li>
<li class="chapter" data-level="8.9.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-difference-between-correlated-groups-t-test-and-correlation"><i class="fa fa-check"></i><b>8.9.3</b> Difference Between Correlated Groups T Test and Correlation</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="section-hypotest.html"><a href="section-hypotest.html#section-regression"><i class="fa fa-check"></i><b>8.10</b> Regression</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-a-regression"><i class="fa fa-check"></i><b>8.10.1</b> When to Use A Regression</a></li>
<li class="chapter" data-level="8.10.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-regression"><i class="fa fa-check"></i><b>8.10.2</b> Conducting and Interpreting the Regression</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="section-hypotest.html"><a href="section-hypotest.html#section-chi-square-test-of-goodness-of-fit"><i class="fa fa-check"></i><b>8.11</b> Chi-square Test of Goodness of Fit</a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-chi-square-test-of-goodness-of-fit"><i class="fa fa-check"></i><b>8.11.1</b> When to Use Chi-square Test of Goodness of Fit</a></li>
<li class="chapter" data-level="8.11.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-chi-square-test-of-goodness-of-fit"><i class="fa fa-check"></i><b>8.11.2</b> Conducting and Interpreting the Chi-Square Test of Goodness of Fit</a></li>
<li class="chapter" data-level="8.11.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-cohens-w"><i class="fa fa-check"></i><b>8.11.3</b> Effect Size: Cohen’s w</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="section-hypotest.html"><a href="section-hypotest.html#section-chi-square-test-of-independence"><i class="fa fa-check"></i><b>8.12</b> Chi-square Test of Independence</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="section-hypotest.html"><a href="section-hypotest.html#section-when-to-use-chi-square-test-of-independence"><i class="fa fa-check"></i><b>8.12.1</b> When to Use Chi-square Test of Independence</a></li>
<li class="chapter" data-level="8.12.2" data-path="section-hypotest.html"><a href="section-hypotest.html#section-conducting-and-interpreting-the-chi-square-test-of-independence"><i class="fa fa-check"></i><b>8.12.2</b> Conducting and Interpreting the Chi-square Test of Independence</a></li>
<li class="chapter" data-level="8.12.3" data-path="section-hypotest.html"><a href="section-hypotest.html#section-effect-size-phi"><i class="fa fa-check"></i><b>8.12.3</b> Effect Size: Phi</a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="section-hypotest.html"><a href="section-hypotest.html#section-next-steps"><i class="fa fa-check"></i><b>8.13</b> Next steps</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC208 R Companion Website</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-hypotest" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Hypothesis Testing<a href="section-hypotest.html#section-hypotest" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="section-overview-1" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Overview<a href="section-hypotest.html#section-overview-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The bulk of what we cover in PSYC208 is hypothesis testing.
This section guides you through the steps of conducting the various hypothesis tests. This only serves as an overview for students who are interested to read ahead. I will demonstrate how to conduct the hypothesis tests in class as well as how to interpret the results.</p>
<p>To illustrate the various tests, we will use the same hypothetical dataset, <code>SWB.csv</code> as before. To follow along, please download the dataset: <a href="SWB.csv">SWB.csv</a>.</p>
</div>
<div id="section-load-packages-and-dataset" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Load Packages and Dataset<a href="section-hypotest.html#section-load-packages-and-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="section-cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb83-1"><a href="section-hypotest.html#section-cb83-1" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="section-cb83-2"><a href="section-hypotest.html#section-cb83-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="section-cb83-3"><a href="section-hypotest.html#section-cb83-3" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="section-cb83-4"><a href="section-hypotest.html#section-cb83-4" tabindex="-1"></a></span>
<span id="section-cb83-5"><a href="section-hypotest.html#section-cb83-5" tabindex="-1"></a><span class="co"># Read in the dataset</span></span>
<span id="section-cb83-6"><a href="section-hypotest.html#section-cb83-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;SWB.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="section-scientific-notation" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Scientific Notation<a href="section-hypotest.html#section-scientific-notation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to loading the packages and reading in the data file, it might also be helpful to run the code below to turn off scientific notation.</p>
<div class="sourceCode" id="section-cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb84-1"><a href="section-hypotest.html#section-cb84-1" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)  <span class="co"># Turn off scientific notation </span></span>
<span id="section-cb84-2"><a href="section-hypotest.html#section-cb84-2" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">9</span>)  <span class="co"># Display results to 9 decimal places</span></span></code></pre></div>
<p>Scientific notation is a way of expressing numbers that are very large or very small. It usually takes the form of <code>m × 10^n</code> for very large numbers and <code>m × 10^-n</code> for very small numbers, where <code>^</code> stands for “to the power of”. So, suppose we have the following number: 0.000000000000000477. In scientific notation, this would be represented as<code>4.77 x 10^-16</code> (i.e., 16 decimal places). Alternatively, it might be represented as <code>4.77e-16</code>. They mean the same thing.</p>
<p>Here’s a quick question to see if you understood scientific notation. Which of the following is the scientific notation for 0.0123?</p>
<ol style="list-style-type: upper-alpha">
<li>1.23e-1 / 1.23 x 10^-1</li>
<li>1.23e-2 / 1.23 x 10^-2</li>
<li>1.23e-3 / 1.23 x 10^-3</li>
<li>1.23e-4 / 1.23 x 10^-4</li>
</ol>
<p>(Answer after the next paragraph because I couldn’t find a better way to hide the answer!)</p>
<p>By default, R presents very small or very large numbers in scientific notation. However, this can be difficult to understand for people who don’t use scientific notation in their daily lives. I confess I have difficulty with scientific notation myself so I usually turn the scientific notation off. It’s really a matter of personal choice whether you want to turn it off or not, though! Just thought you’d like an option :)</p>
<div class="sourceCode" id="section-cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb85-1"><a href="section-hypotest.html#section-cb85-1" tabindex="-1"></a><span class="co"># Answer to the quiz above is Option B: 1.23e-2 / 1.23 x 10^-2.</span></span></code></pre></div>
<p>And now, let’s begin with the hypothesis tests!</p>
</div>
<div id="section-one-sample-t-test" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> One-Sample T Test<a href="section-hypotest.html#section-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-one-sample-t-test" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> When to Use A One-Sample T Test<a href="section-hypotest.html#section-when-to-use-a-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use a one-sample t test when we want to compare the data from one group to some hypothesised mean. You can think of it as taking a set of observations or scores and then comparing it to some value.</p>
<p>So, suppose we’re interested to know whether on average, in 2019, people were more or less satisfied with their lives than the neutral value of 4. (Why 4? Well, in this data set, the satisfaction with life items were measured on a 7-point scale, where 4 is the neutral point.) To answer this question, we will conduct a one-sample t test.</p>
</div>
<div id="section-conducting-and-interpreting-the-one-sample-t-test" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Conducting and Interpreting the One-Sample T Test<a href="section-hypotest.html#section-conducting-and-interpreting-the-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before jumping into any hypothesis testing, though, it is good practice to first get the descriptive statistics for the variable(s) you’re investigating. At the minimum, you should get the mean and the standard deviation. (Anyway, you need to report means and standard deviations in APA style write-up!) I often also like to look at the minimum and maximum values to make sure the values are not out of ordinary (e.g., a value of -999 might throw up some red flags if, say, the likert scale only comprises values from 1 to 7).</p>
<div class="sourceCode" id="section-cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb86-1"><a href="section-hypotest.html#section-cb86-1" tabindex="-1"></a><span class="co"># Calculate the average satisfaction with life score in 2019 for each participant</span></span>
<span id="section-cb86-2"><a href="section-hypotest.html#section-cb86-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="section-cb86-3"><a href="section-hypotest.html#section-cb86-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swls2019_avg =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(swls2019_1<span class="sc">:</span>swls2019_5))))</span>
<span id="section-cb86-4"><a href="section-hypotest.html#section-cb86-4" tabindex="-1"></a></span>
<span id="section-cb86-5"><a href="section-hypotest.html#section-cb86-5" tabindex="-1"></a><span class="co"># Get the descriptive statistics</span></span>
<span id="section-cb86-6"><a href="section-hypotest.html#section-cb86-6" tabindex="-1"></a><span class="fu">describe</span>(df<span class="sc">$</span>swls2019_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 4.35 0.77    4.4    4.33 0.89   2   6     4  0.1    -0.48 0.04</code></pre>
<p>Then, we can conduct the t test.</p>
<div class="sourceCode" id="section-cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb88-1"><a href="section-hypotest.html#section-cb88-1" tabindex="-1"></a><span class="co"># Conduct the one-sample t test to </span></span>
<span id="section-cb88-2"><a href="section-hypotest.html#section-cb88-2" tabindex="-1"></a><span class="co"># compare the satisfaction with life score in 2019 against </span></span>
<span id="section-cb88-3"><a href="section-hypotest.html#section-cb88-3" tabindex="-1"></a><span class="co"># the neutral point of 4</span></span>
<span id="section-cb88-4"><a href="section-hypotest.html#section-cb88-4" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> df<span class="sc">$</span>swls2019_avg,  <span class="co"># variable we&#39;re analysing</span></span>
<span id="section-cb88-5"><a href="section-hypotest.html#section-cb88-5" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">4</span>)  <span class="co"># value we&#39;re comparing against</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$swls2019_avg
## t = 8.530937, df = 342, p-value = 0.000000000000000477477
## alternative hypothesis: true mean is not equal to 4
## 95 percent confidence interval:
##  4.27188244 4.43482310
## sample estimates:
##  mean of x 
## 4.35335277</code></pre>
<div class="sourceCode" id="section-cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb90-1"><a href="section-hypotest.html#section-cb90-1" tabindex="-1"></a><span class="co"># By default, R assumes a two-tailed test, </span></span>
<span id="section-cb90-2"><a href="section-hypotest.html#section-cb90-2" tabindex="-1"></a><span class="co"># that each observation comes from different individuals (i.e., they are not &quot;paired&quot;), </span></span>
<span id="section-cb90-3"><a href="section-hypotest.html#section-cb90-3" tabindex="-1"></a><span class="co"># and that the alpha level is .05, therefore confidence interval is 95%</span></span></code></pre></div>
<p>The results tell you that the average of <code>swls2019_avg</code> is 4.35 (but notice it doesn’t tell you any other descriptive statistics like standard deviation or maximum, so it’s still important to get the descriptives in other ways).</p>
<p>When we compare 4.35 to the neutral point of 4, the resulting t value is 8.53. With degrees of freedom 342, the <em>p</em> value is very small, at 0.000000000000000477477. Because <em>p</em> value is smaller than the alpha level of .05, the result is statistically significant. Because 4.35 is statistically significantly greater than 4, we would conclude that there is sufficient evidence that the satisfaction with life scores in 2019 is greater than the neutral value of 4.</p>
<p>In addition, the 95% confidence interval is [4.27, 4.43], which is interpreted as follows: We are 95% confident that the population mean 2019 satisfaction with life score is between 4.27 and 4.43.</p>
</div>
<div id="section-effect-size-cohens-d" class="section level3 hasAnchor" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> Effect Size: Cohen’s d<a href="section-hypotest.html#section-effect-size-cohens-d" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In addition to hypothesis testing, we also need to look at (standardised) effect size. Effect sizes tell you how large the effect (or the difference) is. The effect size we usually calculate for t tests is the Cohen’s d. By convention, in psychology, <em>d</em> = 0.2 is considered a small effect size, <em>d</em> = 0.5 is considered a medium effect size, and <em>d</em> = 0.8 is considered a large effect size.</p>
<p>We can calculate Cohen’s d using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb91-1"><a href="section-hypotest.html#section-cb91-1" tabindex="-1"></a><span class="co"># Load package (remember to install package before loading package)</span></span>
<span id="section-cb91-2"><a href="section-hypotest.html#section-cb91-2" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span></code></pre></div>
<pre><code>## Warning: package &#39;effectsize&#39; was built under R version 4.3.2</code></pre>
<div class="sourceCode" id="section-cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb93-1"><a href="section-hypotest.html#section-cb93-1" tabindex="-1"></a><span class="co"># Cohen&#39;s d, with mu = 4 (i.e., the comparison value is 4)</span></span>
<span id="section-cb93-2"><a href="section-hypotest.html#section-cb93-2" tabindex="-1"></a><span class="fu">cohens_d</span>(df<span class="sc">$</span>swls2019_avg, </span>
<span id="section-cb93-3"><a href="section-hypotest.html#section-cb93-3" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
## 0.46      | [0.35, 0.57]
## 
## - Deviation from a difference of 4.</code></pre>
<p>Given the Cohen’s d is 0.46, we can consider this a small to medium effect size. Meaning, there is a small to medium difference between the average 2019 satisfaction with life scores and the neutral point of 4.</p>
</div>
</div>
<div id="section-correlated-groups-t-test" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Correlated Groups T test<a href="section-hypotest.html#section-correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-correlated-groups-t-test" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> When to Use A Correlated Groups T Test<a href="section-hypotest.html#section-when-to-use-a-correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use a correlated groups t test when we want to compare two sets of data to see if they are different from each other. Importantly, the two sets of data are paired or correlated in some way (e.g., they come from the same person).</p>
<p>Suppose we want to know from our hypothetical dataset whether people’s satisfaction with life scores changed from 2019 to 2021. We have (or can calculate) the same individuals’ satisfaction with life scores in 2019 and in 2021. Given the same individual provided the 2019 and the 2021 scores, the two sets of scores are considered paired or correlated.</p>
<p>To find out whether there is a difference between these two sets of (paired) scores, we should therefore conduct a correlated groups t test.</p>
</div>
<div id="section-conducting-and-interpreting-the-correlated-groups-t-test" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Conducting and Interpreting the Correlated Groups T Test<a href="section-hypotest.html#section-conducting-and-interpreting-the-correlated-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Again, before conducting the correlated groups t test, remember to get the descriptive statistics for each set of scores.</p>
<div class="sourceCode" id="section-cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb95-1"><a href="section-hypotest.html#section-cb95-1" tabindex="-1"></a><span class="co"># Calculate the average satisfaction with life score in 2021 for each participant. </span></span>
<span id="section-cb95-2"><a href="section-hypotest.html#section-cb95-2" tabindex="-1"></a><span class="co"># If you did not calculate the average satisfaction with life score in 2019 earlier, you will want to do that before continuing.</span></span>
<span id="section-cb95-3"><a href="section-hypotest.html#section-cb95-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="section-cb95-4"><a href="section-hypotest.html#section-cb95-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swls2021_avg =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(swls2021_1<span class="sc">:</span>swls2021_5))))</span>
<span id="section-cb95-5"><a href="section-hypotest.html#section-cb95-5" tabindex="-1"></a></span>
<span id="section-cb95-6"><a href="section-hypotest.html#section-cb95-6" tabindex="-1"></a><span class="co"># Get the descriptives</span></span>
<span id="section-cb95-7"><a href="section-hypotest.html#section-cb95-7" tabindex="-1"></a><span class="fu">describe</span>(df<span class="sc">$</span>swls2019_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 4.35 0.77    4.4    4.33 0.89   2   6     4  0.1    -0.48 0.04</code></pre>
<div class="sourceCode" id="section-cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb97-1"><a href="section-hypotest.html#section-cb97-1" tabindex="-1"></a><span class="fu">describe</span>(df<span class="sc">$</span>swls2021_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 3.85 0.67    3.8    3.84 0.89   2 5.8   3.8  0.1    -0.37 0.04</code></pre>
<p>From the descriptive statistics results, you’ll notice that the 2019 satisfaction with life scores appear to be higher than that for the 2021 satisfaction with life scores. But we need to conduct the correlated groups t test to find out if this difference is statistically significant.</p>
<div class="sourceCode" id="section-cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb99-1"><a href="section-hypotest.html#section-cb99-1" tabindex="-1"></a><span class="co"># Conduct the correlated groups t test to </span></span>
<span id="section-cb99-2"><a href="section-hypotest.html#section-cb99-2" tabindex="-1"></a><span class="co"># see if there is any significant difference between </span></span>
<span id="section-cb99-3"><a href="section-hypotest.html#section-cb99-3" tabindex="-1"></a><span class="co"># the satisfaction with life scores in 2019 and in 2021. </span></span>
<span id="section-cb99-4"><a href="section-hypotest.html#section-cb99-4" tabindex="-1"></a></span>
<span id="section-cb99-5"><a href="section-hypotest.html#section-cb99-5" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> df<span class="sc">$</span>swls2019_avg,  <span class="co"># scores in 2019 </span></span>
<span id="section-cb99-6"><a href="section-hypotest.html#section-cb99-6" tabindex="-1"></a>       <span class="at">y =</span> df<span class="sc">$</span>swls2021_avg,  <span class="co"># scores in 2021</span></span>
<span id="section-cb99-7"><a href="section-hypotest.html#section-cb99-7" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,  <span class="co"># value we expect if null hypothesis of no difference is true</span></span>
<span id="section-cb99-8"><a href="section-hypotest.html#section-cb99-8" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)  <span class="co"># observations are paired, meaning each individual offered pairs of observations (i.e., swls2019_avg and swls2021_avg)</span></span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  df$swls2019_avg and df$swls2021_avg
## t = 27.82957, df = 342, p-value &lt; 0.000000000000000222
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.46493219 0.53565090
## sample estimates:
## mean difference 
##     0.500291545</code></pre>
<div class="sourceCode" id="section-cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb101-1"><a href="section-hypotest.html#section-cb101-1" tabindex="-1"></a><span class="co"># By default, R assumes a two-tailed test, </span></span>
<span id="section-cb101-2"><a href="section-hypotest.html#section-cb101-2" tabindex="-1"></a><span class="co"># and that the alpha level is .05, therefore confidence interval is 95%.</span></span>
<span id="section-cb101-3"><a href="section-hypotest.html#section-cb101-3" tabindex="-1"></a><span class="co"># Since observations are paired, we need to specify that using paired = TRUE.</span></span></code></pre></div>
<p>The results indicate that the average of the difference between swls2019_avg and swls2021_avg is 0.50. When we compare this difference against 0, the resulting t value is 27.83. With degrees of freedom 342, the <em>p</em> value is very small, at 0.000000000000000222. Because <em>p</em> value is smaller than the alpha level of .05, the result is statistically significant. Because 4.35 (mean for 2019) is statistically significantly greater than 3.85 (mean for 2021), we would conclude that there is sufficient evidence that on average, the satisfaction with life scores in 2019 are higher than the satisfaction with life scores in 2021.</p>
<p>The 95% confidence interval is [0.46, 0.54], which is interpreted as follows: We are 95% confident that the population mean difference between the 2019 and 2021 satisfaction with life scores is between 0.46 and 0.54.</p>
</div>
<div id="section-effect-size-cohens-d-1" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> Effect Size: Cohen’s d<a href="section-hypotest.html#section-effect-size-cohens-d-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we need to get the effect size, Cohen’s d, for correlated groups t test using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb102-1"><a href="section-hypotest.html#section-cb102-1" tabindex="-1"></a><span class="co"># Cohen&#39;s d with mu = 0</span></span>
<span id="section-cb102-2"><a href="section-hypotest.html#section-cb102-2" tabindex="-1"></a><span class="fu">cohens_d</span>(<span class="at">x =</span> df<span class="sc">$</span>swls2019_avg,</span>
<span id="section-cb102-3"><a href="section-hypotest.html#section-cb102-3" tabindex="-1"></a>         <span class="at">y =</span> df<span class="sc">$</span>swls2021_avg,</span>
<span id="section-cb102-4"><a href="section-hypotest.html#section-cb102-4" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="section-cb102-5"><a href="section-hypotest.html#section-cb102-5" tabindex="-1"></a>         <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
## 1.50      | [1.35, 1.66]</code></pre>
<p>Given the Cohen’s d is 1.50, we can consider this a large effect size. In other words, there is a large difference between the 2019 and 2021 satisfaction with life scores.</p>
</div>
</div>
<div id="section-independent-groups-t-test" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Independent Groups T Test<a href="section-hypotest.html#section-independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-an-independent-groups-t-test" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> When to Use An Independent Groups T Test<a href="section-hypotest.html#section-when-to-use-an-independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use an independent groups t test when we want to compare two sets of data to see if they are different from each other. Importantly, the two sets of data are independent (i.e., they are NOT paired).</p>
<p>Suppose we want to know whether men and women differ in satisfaction with life in 2019. In other words, we’re comparing the satisfaction with life scores for the group of men with that for the group of women. In this case, because the men and women are not paired with each other in any way, we consider the two sets of satisfaction with life scores as independent.</p>
<p>Therefore, to answer our research question, we will conduct an independent groups t test.</p>
</div>
<div id="section-conducting-and-interpreting-the-independent-groups-t-test" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> Conducting and Interpreting the Independent Groups T Test<a href="section-hypotest.html#section-conducting-and-interpreting-the-independent-groups-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before conducting the independent groups t test, we need to convert the grouping variable into a factor. Here, the grouping variable is gender because we’re comparing the male group against the female group.</p>
<p>After converting the grouping variable into a factor, we also want to get the descriptive statistics for each group.</p>
<div class="sourceCode" id="section-cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb104-1"><a href="section-hypotest.html#section-cb104-1" tabindex="-1"></a><span class="co"># First, we need to convert gender into a factor and add the labels accordingly </span></span>
<span id="section-cb104-2"><a href="section-hypotest.html#section-cb104-2" tabindex="-1"></a>df<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>gender, </span>
<span id="section-cb104-3"><a href="section-hypotest.html#section-cb104-3" tabindex="-1"></a>                      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="section-cb104-4"><a href="section-hypotest.html#section-cb104-4" tabindex="-1"></a>                      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>))</span>
<span id="section-cb104-5"><a href="section-hypotest.html#section-cb104-5" tabindex="-1"></a></span>
<span id="section-cb104-6"><a href="section-hypotest.html#section-cb104-6" tabindex="-1"></a><span class="co"># Next, we get the descriptive statistics for each group, male and female</span></span>
<span id="section-cb104-7"><a href="section-hypotest.html#section-cb104-7" tabindex="-1"></a><span class="fu">describeBy</span>(df<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> df<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: male
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 168 4.08 0.61    4.2    4.06 0.59   3 5.8   2.8 0.26    -0.46 0.05
## ------------------------------------------------------------ 
## group: female
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 175 4.62 0.81    4.6    4.65 0.89   2   6     4 -0.35    -0.25 0.06</code></pre>
<p>The descriptive statistics tell us that on average, the males have lower satisfaction with life scores than females. To find out whether this difference is statistically significant, we need to conduct the independent groups t test.</p>
<div class="sourceCode" id="section-cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb106-1"><a href="section-hypotest.html#section-cb106-1" tabindex="-1"></a><span class="co"># We conduct the independent groups t test to </span></span>
<span id="section-cb106-2"><a href="section-hypotest.html#section-cb106-2" tabindex="-1"></a><span class="co"># determine if men and women differ in </span></span>
<span id="section-cb106-3"><a href="section-hypotest.html#section-cb106-3" tabindex="-1"></a><span class="co"># satisfaction with life in 2019</span></span>
<span id="section-cb106-4"><a href="section-hypotest.html#section-cb106-4" tabindex="-1"></a><span class="fu">t.test</span>(df<span class="sc">$</span>swls2019_avg <span class="sc">~</span> df<span class="sc">$</span>gender,  <span class="co"># DV (outcome) ~ IV (group)</span></span>
<span id="section-cb106-5"><a href="section-hypotest.html#section-cb106-5" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,   <span class="co"># value we expect if null hypothesis of no difference is true </span></span>
<span id="section-cb106-6"><a href="section-hypotest.html#section-cb106-6" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>)  <span class="co"># homogeneity of variance assumption is assumed to be met (if homogeneity of variance is violated, use var.equal = FALSE and R will conduct Welch corrections)</span></span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  df$swls2019_avg by df$gender
## t = -6.898557, df = 341, p-value = 0.0000000000256373
## alternative hypothesis: true difference in means between group male and group female is not equal to 0
## 95 percent confidence interval:
##  -0.689132523 -0.383343668
## sample estimates:
##   mean in group male mean in group female 
##            4.0797619            4.6160000</code></pre>
<div class="sourceCode" id="section-cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb108-1"><a href="section-hypotest.html#section-cb108-1" tabindex="-1"></a><span class="co"># Again... By default, R assumes a two-tailed test, </span></span>
<span id="section-cb108-2"><a href="section-hypotest.html#section-cb108-2" tabindex="-1"></a><span class="co"># that each observation comes from different individuals (i.e., they are not &quot;paired&quot;), </span></span>
<span id="section-cb108-3"><a href="section-hypotest.html#section-cb108-3" tabindex="-1"></a><span class="co"># and that the alpha level is .05, therefore confidence interval is 95%</span></span></code></pre></div>
<p>The results indicate that the average 2019 satisfaction with life score for those who identify as male is 4.08 and 4.62 for those who identify as female. When we compare the difference between the two genders against 0, the resulting t value is -6.90. With degrees of freedom 341, the <em>p</em> value is very small, at 0.0000000000256373. Because <em>p</em> value is smaller than the alpha level of .05, the result is statistically significant. Because 4.62 is statistically significantly greater than 4.08, we would conclude that there is sufficient evidence that the satisfaction with life scores in 2019 is greater for females than for males.</p>
<p>The 95% confidence interval is [-0.69, -0.38] which is interpreted as follows: We are 95% confident that the population mean difference in 2019 satisfaction with life score between males and females is between -0.69 and -0.38.</p>
<p><em>Note.</em> In calculating the t statistic, R took male - female (since 0 = male and 1 = female, and R takes the group coded with the smaller number and subtracts the group coded with the larger number). Because males have a smaller 2019 SWLS than females, the t statistic is negative. However, if R had taken female - male (say if it had been 0 = female and 1 = male), the t statistic would be positive. To me, whether the t statistic is positive or negative doesn’t matter so long as you know which group has a higher mean and therefore can interpret correctly the direction of the effect. (And this is why descriptive statistics is important–it helps you interpret the results accurately!)</p>
</div>
<div id="section-effect-size-cohens-d-2" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> Effect Size: Cohen’s d<a href="section-hypotest.html#section-effect-size-cohens-d-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we need to get the effect size, Cohen’s d, for the independent groups t test using the <code>cohens_d()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb109-1"><a href="section-hypotest.html#section-cb109-1" tabindex="-1"></a><span class="co"># Cohen&#39;s d, with mu = 0</span></span>
<span id="section-cb109-2"><a href="section-hypotest.html#section-cb109-2" tabindex="-1"></a><span class="fu">cohens_d</span>(swls2019_avg <span class="sc">~</span> gender, </span>
<span id="section-cb109-3"><a href="section-hypotest.html#section-cb109-3" tabindex="-1"></a>         <span class="at">data =</span> df, </span>
<span id="section-cb109-4"><a href="section-hypotest.html#section-cb109-4" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |         95% CI
## --------------------------
## -0.75     | [-0.96, -0.53]
## 
## - Estimated using pooled SD.</code></pre>
<p>Given the Cohen’s d is -0.75, we can consider this a medium-large effect size. In other words, there is a medium-large difference in the 2019 satisfaction with life scores between males and females.</p>
<p><em>Note.</em> Again, note that there is a negative sign here because R took <code>male - female</code>. If R took <code>female - male</code>, Cohen’s d will be a positive number. This is not an issue so long as you know which group had a higher mean and can interpret correctly.</p>
</div>
</div>
<div id="section-one-way-between-subjects-anova" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> One-Way Between-Subjects ANOVA<a href="section-hypotest.html#section-one-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-one-way-between-subjects-anova" class="section level3 hasAnchor" number="8.7.1">
<h3><span class="header-section-number">8.7.1</span> When to Use A One-Way Between-Subjects ANOVA<a href="section-hypotest.html#section-when-to-use-a-one-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The independent groups t test is used when you want to compare the scores between two independent groups. But what if you have more than two independent groups? You would use the one-way between-subjects ANOVA.</p>
<p>So, suppose we want to know whether people with different marital status report differing levels of satisfaction with life scores. In other words, we might want to find out whether there is at least one mean difference between: a) married vs divorced, b) married vs widowed, c) divorced vs widowed. To find out, we will conduct the one-way between-subjects ANOVA.</p>
</div>
<div id="section-conducting-and-interpreting-the-one-way-between-subjects-anova" class="section level3 hasAnchor" number="8.7.2">
<h3><span class="header-section-number">8.7.2</span> Conducting and Interpreting the One-Way Between-Subjects ANOVA<a href="section-hypotest.html#section-conducting-and-interpreting-the-one-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before conducting the ANOVA, we need to convert the grouping variable into a factor. Here, the grouping variable is marital status because we grouped the individuals into the three groups: married, widowed, and divorced.</p>
<p>After converting the grouping variable into a factor, we also want to get the descriptive statistics for each group.</p>
<div class="sourceCode" id="section-cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb111-1"><a href="section-hypotest.html#section-cb111-1" tabindex="-1"></a><span class="co"># Convert marital status into factor</span></span>
<span id="section-cb111-2"><a href="section-hypotest.html#section-cb111-2" tabindex="-1"></a>df<span class="sc">$</span>marital_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>marital_status,</span>
<span id="section-cb111-3"><a href="section-hypotest.html#section-cb111-3" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="section-cb111-4"><a href="section-hypotest.html#section-cb111-4" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;married&quot;</span>, <span class="st">&quot;divorced&quot;</span>, <span class="st">&quot;widowed&quot;</span>))</span>
<span id="section-cb111-5"><a href="section-hypotest.html#section-cb111-5" tabindex="-1"></a></span>
<span id="section-cb111-6"><a href="section-hypotest.html#section-cb111-6" tabindex="-1"></a><span class="co"># Get the descriptive statistics by marital status</span></span>
<span id="section-cb111-7"><a href="section-hypotest.html#section-cb111-7" tabindex="-1"></a><span class="fu">describeBy</span>(df<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> df<span class="sc">$</span>marital_status)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: married
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 118 4.58 0.85    4.5     4.6 1.19   3   6     3 -0.01    -1.08 0.08
## ------------------------------------------------------------ 
## group: divorced
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 114 4.16 0.72    4.3    4.16 0.74   2 5.6   3.6 -0.17     -0.1 0.07
## ------------------------------------------------------------ 
## group: widowed
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 111  4.3 0.65    4.4    4.27 0.59 3.2   6   2.8 0.18    -0.74 0.06</code></pre>
<p>From the means, we can see that married people have the highest satisfaction with life scores, followed by widowers and then divorcees. To find out whether the result is statistically significant, we conduct the ANOVA.</p>
<div class="sourceCode" id="section-cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb113-1"><a href="section-hypotest.html#section-cb113-1" tabindex="-1"></a><span class="co"># Run the ANOVA</span></span>
<span id="section-cb113-2"><a href="section-hypotest.html#section-cb113-2" tabindex="-1"></a><span class="co"># Set up the model being tested and store the model to [mod1]</span></span>
<span id="section-cb113-3"><a href="section-hypotest.html#section-cb113-3" tabindex="-1"></a><span class="co"># The model has the following format: DV ~ IV</span></span>
<span id="section-cb113-4"><a href="section-hypotest.html#section-cb113-4" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(swls2019_avg <span class="sc">~</span> marital_status, </span>
<span id="section-cb113-5"><a href="section-hypotest.html#section-cb113-5" tabindex="-1"></a>            <span class="at">data =</span> df)  </span>
<span id="section-cb113-6"><a href="section-hypotest.html#section-cb113-6" tabindex="-1"></a></span>
<span id="section-cb113-7"><a href="section-hypotest.html#section-cb113-7" tabindex="-1"></a><span class="co"># Look at the summary of the results in mod1</span></span>
<span id="section-cb113-8"><a href="section-hypotest.html#section-cb113-8" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>##                 Df   Sum Sq Mean Sq F value      Pr(&gt;F)    
## marital_status   2  10.7832 5.39159 9.62428 0.000085953 ***
## Residuals      340 190.4705 0.56021                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The F ratio is 9.62. With the degrees of freedom 2 and 340, the <em>p</em> value is 0.000085953, which is smaller than our alpha level of .05. Therefore, we conclude that there is sufficient evidence indicating that there is at least one mean difference in 2019 satisfaction with life scores between the three marital statuses.</p>
</div>
<div id="section-posthoc-analysis-tukeys-hsd" class="section level3 hasAnchor" number="8.7.3">
<h3><span class="header-section-number">8.7.3</span> Posthoc Analysis: Tukey’s HSD<a href="section-hypotest.html#section-posthoc-analysis-tukeys-hsd" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because the ANOVA results are statistically significant, we want to follow up with a posthoc analysis such as the Tukey’s HSD to investigate which group(s) differ from which group(s).</p>
<p>The Tukey’s HSD conducts all possible pairwise comparisons, while adjusting the <em>p</em> value to control inflation of family-wise error rate. In this example, we would have three pairwise comparisons: a) married vs widowed, b) married vs divorced, and c) widowed vs divorced.</p>
<div class="sourceCode" id="section-cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb115-1"><a href="section-hypotest.html#section-cb115-1" tabindex="-1"></a><span class="co"># Perform a posthoc test on the results using Tukey&#39;s HSD and get the 95% CI </span></span>
<span id="section-cb115-2"><a href="section-hypotest.html#section-cb115-2" tabindex="-1"></a><span class="fu">TukeyHSD</span>(mod1, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = swls2019_avg ~ marital_status, data = df)
## 
## $marital_status
##                          diff           lwr           upr       p adj
## divorced-married -0.423342254 -0.6547275679 -0.1919569400 0.000064299
## widowed-married  -0.280241258 -0.5132115136 -0.0472710028 0.013569662
## widowed-divorced  0.143100996 -0.0918420376  0.3780440291 0.324684308</code></pre>
<p>The results indicate that married people were significantly more satisfied with their lives than divorced and widowed people. However, divorced and widowed people did not differ significantly in their satisfaction with life scores.</p>
<p><em>Note.</em> Tukey’s HSD is one of the most common posthoc tests. But there are others. If you need other posthoc tests, you might want to check out the <code>DescTools</code> package.</p>
</div>
<div id="section-effect-size-eta-squared" class="section level3 hasAnchor" number="8.7.4">
<h3><span class="header-section-number">8.7.4</span> Effect Size: Eta-Squared<a href="section-hypotest.html#section-effect-size-eta-squared" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like the t tests, we need to calculate the effect size for ANOVA to see how large the effect is. One of the most commonly reported effect sizes for ANOVA is eta-squared (η2). By convention, <em>η2</em> = 0.01 indicates a small effect, <em>η2</em> = 0.06 indicates a medium effect, and <em>η2</em> = 0.14 indicates a large effect.</p>
<p>We can get eta-squared using the <code>eta_squared()</code> function from <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb117-1"><a href="section-hypotest.html#section-cb117-1" tabindex="-1"></a><span class="fu">eta_squared</span>(mod1, <span class="at">partial =</span> <span class="cn">FALSE</span>)  </span></code></pre></div>
<pre><code>## # Effect Size for ANOVA (Type I)
## 
## Parameter      | Eta2 |       95% CI
## ------------------------------------
## marital_status | 0.05 | [0.02, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<div class="sourceCode" id="section-cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb119-1"><a href="section-hypotest.html#section-cb119-1" tabindex="-1"></a><span class="co"># partial = FALSE means we do NOT want partial eta-squared. </span></span>
<span id="section-cb119-2"><a href="section-hypotest.html#section-cb119-2" tabindex="-1"></a><span class="co"># This actually doesn&#39;t matter here, since for a one-way between-subjects ANOVA, eta-squared and partial eta-squared will be exactly the same value.</span></span></code></pre></div>
<p>The eta-squared value here is .05, suggesting a small to medium effect. In other words, there is a small to medium effect of marital status on satisfaction with life scores.</p>
<p><em>Note.</em> Eta-squared tends to overestimate the effect size. This means it will tell you that the differences between the groups are larger than they actually are. Therefore, non-biased alternatives have been developed in place of eta-squared. This would include omega-squared (ω2) and epsilon-squared (ε2), which you can find in the <code>effectsizes</code> package as well (look for <code>omega_squared()</code> and <code>epsilon_squared()</code>). Omega-squared is more frequently used than epsilon-squared, so if you want to report an unbiased effect size, choose omega-squared.</p>
</div>
</div>
<div id="section-two-way-between-subjects-factorial-anova" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Two-Way Between-Subjects Factorial ANOVA<a href="section-hypotest.html#section-two-way-between-subjects-factorial-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-two-way-between-subjects-factorial-anova" class="section level3 hasAnchor" number="8.8.1">
<h3><span class="header-section-number">8.8.1</span> When to Use A Two-Way Between-Subjects Factorial ANOVA<a href="section-hypotest.html#section-when-to-use-a-two-way-between-subjects-factorial-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A two-way between-subjects ANOVA is used when we want to examine an interaction. In other words, it is used when we’re trying to investigate whether the effect of one variable depends on a second variable (which is usually called a moderator).</p>
<p>Let’s say we’re investigating the effect of alcohol on aggression levels. We think that for men, ingesting alcohol makes them more aggressive (compared to not ingesting alcohol). However, for women, ingesting alcohol does not lead to any change in aggression levels (compared to not ingesting alcohol). In such a case, we’re interested in an interaction: We want to know whether the effect of alcohol on aggression (the difference between ingesting and not ingesting alcohol) depends on biological sex.</p>
<p>There are many kinds of factorial ANOVAs. A between-subjects ANOVA is used when the observations are all independent of each other (i.e., they are not paired or correlated). (If the observations are paired or related, we would use either repeated measures or mixed ANOVA. These would follow different procedures than shown below.)</p>
<p>So, suppose we want to know whether the difference in satisfaction with life scores between male and female depends on whether they have children. To find out, we will need to conduct a two-way between-subjects ANOVA.</p>
</div>
<div id="section-conducting-and-interpreting-the-two-way-between-subjects-anova" class="section level3 hasAnchor" number="8.8.2">
<h3><span class="header-section-number">8.8.2</span> Conducting and Interpreting the Two-Way Between-Subjects ANOVA<a href="section-hypotest.html#section-conducting-and-interpreting-the-two-way-between-subjects-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We need the <code>Anova()</code> function from the <code>car</code> package to run this type of ANOVA. So, we need to load the package, change the grouping variables into factors, and get the descriptives for each group.</p>
<div class="sourceCode" id="section-cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb120-1"><a href="section-hypotest.html#section-cb120-1" tabindex="-1"></a><span class="co"># Load package (remember to install if you&#39;ve not done so!)</span></span>
<span id="section-cb120-2"><a href="section-hypotest.html#section-cb120-2" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Warning: package &#39;car&#39; was built under R version 4.3.2</code></pre>
<pre><code>## Warning: package &#39;carData&#39; was built under R version 4.3.1</code></pre>
<div class="sourceCode" id="section-cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb123-1"><a href="section-hypotest.html#section-cb123-1" tabindex="-1"></a><span class="co"># Change have_children into a factor</span></span>
<span id="section-cb123-2"><a href="section-hypotest.html#section-cb123-2" tabindex="-1"></a><span class="co"># If you&#39;ve not already done so, you&#39;ll also need to change marital status to a factor</span></span>
<span id="section-cb123-3"><a href="section-hypotest.html#section-cb123-3" tabindex="-1"></a>df<span class="sc">$</span>have_children <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>have_children,</span>
<span id="section-cb123-4"><a href="section-hypotest.html#section-cb123-4" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="section-cb123-5"><a href="section-hypotest.html#section-cb123-5" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;no children&quot;</span>, <span class="st">&quot;have children&quot;</span>))</span>
<span id="section-cb123-6"><a href="section-hypotest.html#section-cb123-6" tabindex="-1"></a></span>
<span id="section-cb123-7"><a href="section-hypotest.html#section-cb123-7" tabindex="-1"></a><span class="co"># Get descriptive statistics for each group</span></span>
<span id="section-cb123-8"><a href="section-hypotest.html#section-cb123-8" tabindex="-1"></a><span class="fu">describeBy</span>(df<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> df<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: male
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 168 4.08 0.61    4.2    4.06 0.59   3 5.8   2.8 0.26    -0.46 0.05
## ------------------------------------------------------------ 
## group: female
##    vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 175 4.62 0.81    4.6    4.65 0.89   2   6     4 -0.35    -0.25 0.06</code></pre>
<div class="sourceCode" id="section-cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb125-1"><a href="section-hypotest.html#section-cb125-1" tabindex="-1"></a><span class="fu">describeBy</span>(df<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> df<span class="sc">$</span>have_children)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: no children
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 169 4.09 0.66    4.2    4.06 0.89 2.8 5.8     3 0.38     -0.4 0.05
## ------------------------------------------------------------ 
## group: have children
##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 174 4.61 0.78    4.6    4.63 0.89   2   6     4 -0.3    -0.06 0.06</code></pre>
<div class="sourceCode" id="section-cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb127-1"><a href="section-hypotest.html#section-cb127-1" tabindex="-1"></a><span class="fu">describeBy</span>(df<span class="sc">$</span>swls2019_avg, <span class="at">group =</span> <span class="fu">list</span>(df<span class="sc">$</span>gender, df<span class="sc">$</span>have_children))</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## : male
## : no children
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 92 3.95 0.59      4    3.94 0.74   3 5.8   2.8 0.32    -0.53 0.06
## ------------------------------------------------------------ 
## : female
## : no children
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 77 4.25 0.71    4.4    4.21 0.89 2.8 5.8     3 0.25    -0.63 0.08
## ------------------------------------------------------------ 
## : male
## : have children
##    vars  n mean  sd median trimmed  mad min max range skew kurtosis   se
## X1    1 76 4.23 0.6    4.4    4.21 0.59   3 5.8   2.8 0.19    -0.42 0.07
## ------------------------------------------------------------ 
## : female
## : have children
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 98 4.91 0.77    4.8    4.97 0.89   2   6     4 -1.02     1.75 0.08</code></pre>
<p>Now that we have the descriptives (which will help us interpret the results later on), we can move on to conduct the ANOVA.</p>
<div class="sourceCode" id="section-cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb129-1"><a href="section-hypotest.html#section-cb129-1" tabindex="-1"></a><span class="co"># Change contrasts settings when estimating Type-3 sum of squares</span></span>
<span id="section-cb129-2"><a href="section-hypotest.html#section-cb129-2" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&#39;contr.sum&#39;</span>, <span class="st">&#39;contr.poly&#39;</span>))</span>
<span id="section-cb129-3"><a href="section-hypotest.html#section-cb129-3" tabindex="-1"></a></span>
<span id="section-cb129-4"><a href="section-hypotest.html#section-cb129-4" tabindex="-1"></a><span class="co"># Set up the model being tested and store the model to [mod2]</span></span>
<span id="section-cb129-5"><a href="section-hypotest.html#section-cb129-5" tabindex="-1"></a><span class="co"># The model has the following format: DV ~ IV1 + IV2 + IV1*IV2</span></span>
<span id="section-cb129-6"><a href="section-hypotest.html#section-cb129-6" tabindex="-1"></a><span class="co"># You can actually omit IV1 and IV2 and it would still run the factorial ANOVA</span></span>
<span id="section-cb129-7"><a href="section-hypotest.html#section-cb129-7" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(swls2019_avg <span class="sc">~</span> gender <span class="sc">+</span> have_children <span class="sc">+</span> gender<span class="sc">*</span>have_children, </span>
<span id="section-cb129-8"><a href="section-hypotest.html#section-cb129-8" tabindex="-1"></a>            <span class="at">data =</span> df) </span>
<span id="section-cb129-9"><a href="section-hypotest.html#section-cb129-9" tabindex="-1"></a></span>
<span id="section-cb129-10"><a href="section-hypotest.html#section-cb129-10" tabindex="-1"></a><span class="co"># Conduct Two-Way ANOVA and get the ANOVA summary table</span></span>
<span id="section-cb129-11"><a href="section-hypotest.html#section-cb129-11" tabindex="-1"></a><span class="co"># type = &quot;3&quot; refers to Type 3 sum of squares. There are different types of sum of squares depending on how the sum of squares is partitioned.  </span></span>
<span id="section-cb129-12"><a href="section-hypotest.html#section-cb129-12" tabindex="-1"></a><span class="co"># We will use Type 3 sum of squares as we want to test for an interaction.</span></span>
<span id="section-cb129-13"><a href="section-hypotest.html#section-cb129-13" tabindex="-1"></a><span class="fu">Anova</span>(mod2, <span class="at">type =</span> <span class="st">&quot;3&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: swls2019_avg
##                        Sum Sq  Df     F value                 Pr(&gt;F)    
## (Intercept)          6366.863   1 13955.51399 &lt; 0.000000000000000222 ***
## gender                 19.801   1    43.40250       0.00000000017028 ***
## have_children          18.578   1    40.72079       0.00000000057671 ***
## gender:have_children    3.093   1     6.77873              0.0096307 ** 
## Residuals             154.660 339                                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><em>Note.</em> Read up more on the three types of sum of squares here: <a href="https://towardsdatascience.com/anovas-three-types-of-estimating-sums-of-squares-don-t-make-the-wrong-choice-91107c77a27a" class="uri">https://towardsdatascience.com/anovas-three-types-of-estimating-sums-of-squares-don-t-make-the-wrong-choice-91107c77a27a</a>. tldr: if we are trying to test an interaction, we should use Type 3 sum of squares.</p>
<p>From the results, we can see that the main effects as well as the interaction effect are statistically significant. To interpret the results, we need to look at the descriptive statistics. The main effect of gender tells us that overall, females reported being significantly more satisfied than males (first set of descriptives). The main effect of presence of children tells us that overall, those with children reported being significantly more satisfied than those without children (second set of descriptives). The interaction effect tells us that the effect of gender on satisfaction with life scores depends on the presence of children.</p>
</div>
<div id="section-conducting-and-interpreting-the-simple-effects-analysis" class="section level3 hasAnchor" number="8.8.3">
<h3><span class="header-section-number">8.8.3</span> Conducting and Interpreting the Simple Effects Analysis<a href="section-hypotest.html#section-conducting-and-interpreting-the-simple-effects-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because the interaction is statistically significant, we will follow up with the simple effects analysis. This is essentially like conducting independent groups t tests (with some corrections). Since we want to find out whether the difference in satisfaction with life scores between males and females depends on having children, we will test the: 1) difference in the satisfaction with life scores of males and females who have children; 2) difference in the satisfaction with life scores of males and females who do not have children.</p>
<p>To do the simple effects analyses, we need the <code>emmeans</code> package.</p>
<div class="sourceCode" id="section-cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb131-1"><a href="section-hypotest.html#section-cb131-1" tabindex="-1"></a><span class="co"># Load package (install package if you&#39;ve not already done so)</span></span>
<span id="section-cb131-2"><a href="section-hypotest.html#section-cb131-2" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code></pre></div>
<pre><code>## Warning: package &#39;emmeans&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="section-cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb133-1"><a href="section-hypotest.html#section-cb133-1" tabindex="-1"></a><span class="co"># First, let&#39;s look at a plot of the means for the four groups</span></span>
<span id="section-cb133-2"><a href="section-hypotest.html#section-cb133-2" tabindex="-1"></a><span class="co"># The four groups being: males with children, males without children, females with children, and females without children</span></span>
<span id="section-cb133-3"><a href="section-hypotest.html#section-cb133-3" tabindex="-1"></a><span class="fu">emmip</span>(mod2, have_children <span class="sc">~</span> gender) <span class="co"># Separate Lines: have_children, X axis: gender</span></span></code></pre></div>
<p><img src="PSYC208_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>In the plot, the x axis is gender and the four points represent the means for each condition (i.e., male without children, male with children, female without children, and female with children). The red line represents the difference between male and female who have no children whereas the blue line represents the difference between male and female who have children. Here, we can see that the blue line is steeper than the red line, indicating that the effect of gender (difference between males and females) is bigger for those who have children than for those who don’t have children. This is what the significant interaction effect in the ANOVA is telling us–that the effect of gender is different for those who have children and those who don’t.</p>
<p>Now, we conduct the simple effects analysis to find out if there is a difference a) between males and females with children and b) between males and females without children. This is because even though it looks like there are differences on the graph (e.g., the red line is not flat), we don’t know whether the differences are statistically significant.</p>
<p>We conduct the simple effects analysis using the <code>emmeans()</code> function from the <code>emmeans</code> package.</p>
<div class="sourceCode" id="section-cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb134-1"><a href="section-hypotest.html#section-cb134-1" tabindex="-1"></a><span class="co"># We conduct the simple effects investigating 1) the effect of gender (difference between males and females) for those who have children, and 2) the effect of gender for those who do not have children.  </span></span>
<span id="section-cb134-2"><a href="section-hypotest.html#section-cb134-2" tabindex="-1"></a><span class="fu">emmeans</span>(mod2, pairwise <span class="sc">~</span> gender <span class="sc">|</span> have_children)  <span class="co"># comparing the pair of conditions in gender for each level of have_children</span></span></code></pre></div>
<pre><code>## $emmeans
## have_children = no children:
##  gender emmean     SE  df lower.CL upper.CL
##  male     3.95 0.0704 339     3.82     4.09
##  female   4.25 0.0770 339     4.10     4.40
## 
## have_children = have children:
##  gender emmean     SE  df lower.CL upper.CL
##  male     4.23 0.0775 339     4.08     4.38
##  female   4.91 0.0682 339     4.77     5.04
## 
## Confidence level used: 0.95 
## 
## $contrasts
## have_children = no children:
##  contrast      estimate    SE  df t.ratio p.value
##  male - female   -0.292 0.104 339  -2.803  0.0054
## 
## have_children = have children:
##  contrast      estimate    SE  df t.ratio p.value
##  male - female   -0.675 0.103 339  -6.534  &lt;.0001</code></pre>
<p>The results under <code>$contrasts</code> indicate that females with children have significantly higher satisfaction with life scores than males with children. Similarly, females without children have significantly higher satisfaction with life scores than males without children. (Although, remember, as the interaction effect tells us, the effect of gender for those with children is significantly stronger/larger than that for those without children.)</p>
<p>Suppose, though, you were interested in looking at the effect of having children by gender. (This means your moderator is now gender instead of presence of children.) In other words, you’re interested in looking at the difference 1) between males with and males without children, and 2) between females with and females without children. In this case, you will swap the variables around.</p>
<div class="sourceCode" id="section-cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb136-1"><a href="section-hypotest.html#section-cb136-1" tabindex="-1"></a><span class="co"># First, let&#39;s look at a plot</span></span>
<span id="section-cb136-2"><a href="section-hypotest.html#section-cb136-2" tabindex="-1"></a><span class="co"># Separate Lines: gender, X axis: have_children</span></span>
<span id="section-cb136-3"><a href="section-hypotest.html#section-cb136-3" tabindex="-1"></a><span class="fu">emmip</span>(mod2, gender <span class="sc">~</span> have_children)</span></code></pre></div>
<p><img src="PSYC208_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb137-1"><a href="section-hypotest.html#section-cb137-1" tabindex="-1"></a><span class="co"># Next, we conduct the simple effects investigating 1) the effect of having children (difference between having children and not having children) for males, and 2) the effect of having children (difference between having children and not having children) for females.  </span></span>
<span id="section-cb137-2"><a href="section-hypotest.html#section-cb137-2" tabindex="-1"></a><span class="fu">emmeans</span>(mod2, pairwise <span class="sc">~</span> have_children <span class="sc">|</span> gender)  <span class="co"># comparing the pair of conditions in have_children for each level of gender</span></span></code></pre></div>
<pre><code>## $emmeans
## gender = male:
##  have_children emmean     SE  df lower.CL upper.CL
##  no children     3.95 0.0704 339     3.82     4.09
##  have children   4.23 0.0775 339     4.08     4.38
## 
## gender = female:
##  have_children emmean     SE  df lower.CL upper.CL
##  no children     4.25 0.0770 339     4.10     4.40
##  have children   4.91 0.0682 339     4.77     5.04
## 
## Confidence level used: 0.95 
## 
## $contrasts
## gender = male:
##  contrast                    estimate    SE  df t.ratio p.value
##  no children - have children   -0.277 0.105 339  -2.648  0.0085
## 
## gender = female:
##  contrast                    estimate    SE  df t.ratio p.value
##  no children - have children   -0.659 0.103 339  -6.410  &lt;.0001</code></pre>
<p>The results under <code>$contrasts</code> now indicate that females with children have significantly higher satisfaction with life scores than females without children. Similarly, males with children have significantly higher satisfaction with life scores than males without children. (Note that the interaction effect tells us, the effect of having children for women is significantly stronger/larger than the effect of having children for men.)</p>
</div>
<div id="section-effect-size-partial-eta-squared" class="section level3 hasAnchor" number="8.8.4">
<h3><span class="header-section-number">8.8.4</span> Effect Size: Partial Eta-Squared<a href="section-hypotest.html#section-effect-size-partial-eta-squared" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can get the effect size, partial eta-squared (η2p), for each of the main effects as well as the interaction effect using the <code>eta_squared()</code> function from <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb139-1"><a href="section-hypotest.html#section-cb139-1" tabindex="-1"></a><span class="fu">eta_squared</span>(<span class="fu">Anova</span>(mod2, <span class="at">type =</span> <span class="st">&quot;3&quot;</span>), <span class="at">partial =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Type 3 ANOVAs only give sensible and informative results when covariates
##   are mean-centered and factors are coded with orthogonal contrasts (such
##   as those produced by `contr.sum`, `contr.poly`, or `contr.helmert`, but
##   *not* by the default `contr.treatment`).</code></pre>
<pre><code>## # Effect Size for ANOVA (Type III)
## 
## Parameter            | Eta2 (partial) |       95% CI
## ----------------------------------------------------
## gender               |           0.11 | [0.07, 1.00]
## have_children        |           0.11 | [0.06, 1.00]
## gender:have_children |           0.02 | [0.00, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<p>The results indicate that we have a large effect for gender, a medium-large effect for having children, and a small effect for the interaction.</p>
</div>
</div>
<div id="section-correlation" class="section level2 hasAnchor" number="8.9">
<h2><span class="header-section-number">8.9</span> Correlation<a href="section-hypotest.html#section-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-correlation" class="section level3 hasAnchor" number="8.9.1">
<h3><span class="header-section-number">8.9.1</span> When to Use A Correlation<a href="section-hypotest.html#section-when-to-use-a-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A correlation is used when we want to examine whether two continuous variables are related to each other. Suppose we want to find out whether people who have higher satisfaction with life scores in 2019 also have higher satisfaction with life scores in 2021. Here is where you will conduct a correlation.</p>
</div>
<div id="section-conducting-and-interpreting-the-correlation" class="section level3 hasAnchor" number="8.9.2">
<h3><span class="header-section-number">8.9.2</span> Conducting and Interpreting the Correlation<a href="section-hypotest.html#section-conducting-and-interpreting-the-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As usual, we get the descriptive statistics before conducting the hypothesis test.</p>
<div class="sourceCode" id="section-cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb142-1"><a href="section-hypotest.html#section-cb142-1" tabindex="-1"></a><span class="co"># Get the descriptive statistics</span></span>
<span id="section-cb142-2"><a href="section-hypotest.html#section-cb142-2" tabindex="-1"></a><span class="fu">describe</span>(df<span class="sc">$</span>swls2019_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 4.35 0.77    4.4    4.33 0.89   2   6     4  0.1    -0.48 0.04</code></pre>
<div class="sourceCode" id="section-cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb144-1"><a href="section-hypotest.html#section-cb144-1" tabindex="-1"></a><span class="fu">describe</span>(df<span class="sc">$</span>swls2021_avg)</span></code></pre></div>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 343 3.85 0.67    3.8    3.84 0.89   2 5.8   3.8  0.1    -0.37 0.04</code></pre>
<div class="sourceCode" id="section-cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb146-1"><a href="section-hypotest.html#section-cb146-1" tabindex="-1"></a><span class="co"># Conduct the correlation with cor.test</span></span>
<span id="section-cb146-2"><a href="section-hypotest.html#section-cb146-2" tabindex="-1"></a><span class="co"># Unlike cor(), cor.test() gives you the p value</span></span>
<span id="section-cb146-3"><a href="section-hypotest.html#section-cb146-3" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>swls2019_avg, df<span class="sc">$</span>swls2021_avg)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df$swls2019_avg and df$swls2021_avg
## t = 38.39589, df = 341, p-value &lt; 0.000000000000000222
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.879200201 0.919351528
## sample estimates:
##         cor 
## 0.901191727</code></pre>
<p>The correlation is r = 0.90, with a 95% confidence interval [0.88, 0.92]. The <em>p</em> value is very small, smaller than .05, and so we will conclude that the relationship is positive. In other words, people who have higher satisfaction with life scores in 2019 also have higher satisfaction with life scores in 2021.</p>
<p>There are other ways we can write the R code. Here are two alternatives.</p>
<div class="sourceCode" id="section-cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb148-1"><a href="section-hypotest.html#section-cb148-1" tabindex="-1"></a><span class="co"># Alternative 1</span></span>
<span id="section-cb148-2"><a href="section-hypotest.html#section-cb148-2" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="sc">~</span> swls2019_avg <span class="sc">+</span> swls2021_avg, </span>
<span id="section-cb148-3"><a href="section-hypotest.html#section-cb148-3" tabindex="-1"></a>         <span class="at">data =</span> df)</span>
<span id="section-cb148-4"><a href="section-hypotest.html#section-cb148-4" tabindex="-1"></a></span>
<span id="section-cb148-5"><a href="section-hypotest.html#section-cb148-5" tabindex="-1"></a><span class="co"># Alternative 2</span></span>
<span id="section-cb148-6"><a href="section-hypotest.html#section-cb148-6" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="section-cb148-7"><a href="section-hypotest.html#section-cb148-7" tabindex="-1"></a>  <span class="fu">cor.test</span>(<span class="at">formula =</span> <span class="sc">~</span> swls2019_avg <span class="sc">+</span> swls2021_avg, .)</span></code></pre></div>
<p>Both ways would give us the same result as the earlier one but neither are intuitive. I personally prefer the much simpler <code>cor.test(df$swls2019_avg, df$swls2021_avg)</code>.</p>
</div>
<div id="section-difference-between-correlated-groups-t-test-and-correlation" class="section level3 hasAnchor" number="8.9.3">
<h3><span class="header-section-number">8.9.3</span> Difference Between Correlated Groups T Test and Correlation<a href="section-hypotest.html#section-difference-between-correlated-groups-t-test-and-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Students sometimes get confused between correlated groups t test and correlation. I’ll attempt to explain the difference below.</p>
<p>Correlated groups t test and correlation have different purposes. Correlated groups t test is used when we are trying to find the <em>difference</em> between two paired scores. For example, whether there is a difference between satisfaction with life scores in 2019 and in 2021. Correlation is used when we are trying to find the <em>relationship</em> between two variables. This would be applied when we’re trying to see whether the higher one variable is, the higher/lower another variable is. It is possible for us to have a correlated groups t test that is not statistically significant and a correlation that is significant when we run both on the same data.</p>
<p>Below is a worked example to illustrate the difference.</p>
<div class="sourceCode" id="section-cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb149-1"><a href="section-hypotest.html#section-cb149-1" tabindex="-1"></a><span class="co"># Two Variables X and Y</span></span>
<span id="section-cb149-2"><a href="section-hypotest.html#section-cb149-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="section-cb149-3"><a href="section-hypotest.html#section-cb149-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="section-cb149-4"><a href="section-hypotest.html#section-cb149-4" tabindex="-1"></a></span>
<span id="section-cb149-5"><a href="section-hypotest.html#section-cb149-5" tabindex="-1"></a><span class="co"># Conduct Correlated Groups T Test</span></span>
<span id="section-cb149-6"><a href="section-hypotest.html#section-cb149-6" tabindex="-1"></a><span class="co"># To see if there is a difference between x and y scores</span></span>
<span id="section-cb149-7"><a href="section-hypotest.html#section-cb149-7" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, </span>
<span id="section-cb149-8"><a href="section-hypotest.html#section-cb149-8" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>, </span>
<span id="section-cb149-9"><a href="section-hypotest.html#section-cb149-9" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  x and y
## t = NaN, df = 4, p-value = NA
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  NaN NaN
## sample estimates:
## mean difference 
##               0</code></pre>
<div class="sourceCode" id="section-cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb151-1"><a href="section-hypotest.html#section-cb151-1" tabindex="-1"></a><span class="co"># Conduct the Correlation</span></span>
<span id="section-cb151-2"><a href="section-hypotest.html#section-cb151-2" tabindex="-1"></a><span class="fu">cor.test</span>(x, y)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 82191237, df = 3, p-value &lt; 0.000000000000000222
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  1 1
## sample estimates:
## cor 
##   1</code></pre>
<p>From the output, you will see that the correlated groups t test is not statistically significant, whereas the correlation is. This is because they’re testing different things.</p>
<p>The correlated groups t test is telling us that on average, there is no difference between x scores and y scores. The correlation is telling us there is a perfect positive relationship between x and y. The two variables increase with a fixed proportion: As x increases, y increases proportionately by 1.</p>
</div>
</div>
<div id="section-regression" class="section level2 hasAnchor" number="8.10">
<h2><span class="header-section-number">8.10</span> Regression<a href="section-hypotest.html#section-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-a-regression" class="section level3 hasAnchor" number="8.10.1">
<h3><span class="header-section-number">8.10.1</span> When to Use A Regression<a href="section-hypotest.html#section-when-to-use-a-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A regression is used when we want to use one variable to predict another. The simplest form of linear regression is called simple linear regression. It only has two variables: one predictor and one outcome. If you have multiple predictors, then we would use a multiple linear regression instead. We will stick with simple linear regression here.</p>
<p>Suppose we want to predict <code>swls2021_avg</code> from <code>swls2019_avg</code>. Here, we want to conduct a simple linear regression as we have one predictor and one outcome.</p>
</div>
<div id="section-conducting-and-interpreting-the-regression" class="section level3 hasAnchor" number="8.10.2">
<h3><span class="header-section-number">8.10.2</span> Conducting and Interpreting the Regression<a href="section-hypotest.html#section-conducting-and-interpreting-the-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As the descriptives have been calculated previously, we will go straight to the regression here.</p>
<div class="sourceCode" id="section-cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb153-1"><a href="section-hypotest.html#section-cb153-1" tabindex="-1"></a><span class="co"># Conduct regression</span></span>
<span id="section-cb153-2"><a href="section-hypotest.html#section-cb153-2" tabindex="-1"></a><span class="co"># the model takes the form of Y ~ X (where Y = outcome, X = predictor)</span></span>
<span id="section-cb153-3"><a href="section-hypotest.html#section-cb153-3" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(df<span class="sc">$</span>swls2021_avg <span class="sc">~</span> df<span class="sc">$</span>swls2019_avg)</span>
<span id="section-cb153-4"><a href="section-hypotest.html#section-cb153-4" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = df$swls2021_avg ~ df$swls2019_avg)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -1.056645 -0.248328 -0.006664  0.193336  0.801654 
## 
## Coefficients:
##                  Estimate Std. Error  t value               Pr(&gt;|t|)    
## (Intercept)     0.4065882  0.0911404  4.46112            0.000011087 ***
## df$swls2019_avg 0.7916825  0.0206189 38.39589 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.292508 on 341 degrees of freedom
## Multiple R-squared:  0.812147,   Adjusted R-squared:  0.811596 
## F-statistic: 1474.24 on 1 and 341 DF,  p-value: &lt; 0.000000000000000222</code></pre>
<p>The results indicate that <code>swls2021_avg</code> significantly predicted <code>swls2019_avg</code> (<em>p</em> value is &lt; 0.000000000000000222).</p>
<p>Unfortunately, the summary doesn’t give us the confidence interval. To get that, we need to specify that we want the confidence interval with the <code>confint()</code> function.</p>
<div class="sourceCode" id="section-cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb155-1"><a href="section-hypotest.html#section-cb155-1" tabindex="-1"></a><span class="co"># To get the 95% confidence interval</span></span>
<span id="section-cb155-2"><a href="section-hypotest.html#section-cb155-2" tabindex="-1"></a><span class="fu">confint</span>(mod3)</span></code></pre></div>
<pre><code>##                       2.5 %      97.5 %
## (Intercept)     0.227320000 0.585856416
## df$swls2019_avg 0.751126141 0.832238772</code></pre>
<p>We interpret the 95% confidence interval as, “We are 95% confident that the population slope is between 0.75 and 0.83.”</p>
<p>There are other ways to code a linear regression. One of those alternatives is shown below.</p>
<div class="sourceCode" id="section-cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb157-1"><a href="section-hypotest.html#section-cb157-1" tabindex="-1"></a><span class="co"># Alternative</span></span>
<span id="section-cb157-2"><a href="section-hypotest.html#section-cb157-2" tabindex="-1"></a></span>
<span id="section-cb157-3"><a href="section-hypotest.html#section-cb157-3" tabindex="-1"></a><span class="co"># Linear regression</span></span>
<span id="section-cb157-4"><a href="section-hypotest.html#section-cb157-4" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="section-cb157-5"><a href="section-hypotest.html#section-cb157-5" tabindex="-1"></a>  <span class="fu">lm</span>(swls2021_avg <span class="sc">~</span> swls2019_avg, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> </span>
<span id="section-cb157-6"><a href="section-hypotest.html#section-cb157-6" tabindex="-1"></a>  <span class="fu">summary</span>(.)</span>
<span id="section-cb157-7"><a href="section-hypotest.html#section-cb157-7" tabindex="-1"></a></span>
<span id="section-cb157-8"><a href="section-hypotest.html#section-cb157-8" tabindex="-1"></a><span class="co"># 95% confidence interval</span></span>
<span id="section-cb157-9"><a href="section-hypotest.html#section-cb157-9" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="section-cb157-10"><a href="section-hypotest.html#section-cb157-10" tabindex="-1"></a>  <span class="fu">lm</span>(swls2021_avg <span class="sc">~</span> swls2019_avg, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> </span>
<span id="section-cb157-11"><a href="section-hypotest.html#section-cb157-11" tabindex="-1"></a>  <span class="fu">confint</span>(.)</span></code></pre></div>
<p>You should get the same result as earlier.</p>
</div>
</div>
<div id="section-chi-square-test-of-goodness-of-fit" class="section level2 hasAnchor" number="8.11">
<h2><span class="header-section-number">8.11</span> Chi-square Test of Goodness of Fit<a href="section-hypotest.html#section-chi-square-test-of-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-chi-square-test-of-goodness-of-fit" class="section level3 hasAnchor" number="8.11.1">
<h3><span class="header-section-number">8.11.1</span> When to Use Chi-square Test of Goodness of Fit<a href="section-hypotest.html#section-when-to-use-chi-square-test-of-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the chi-square test of goodness of fit when we want to compare the the observed frequency distribution of a categorical variable to an expected frequency distribution.</p>
<p>Suppose we know that we have the same proportion of men and women in the Singapore population (i.e., 50% of the population are men, 50% are women). We want to know whether the proportion of men and women in our study (observed frequency distribution) is the same as or different from that of the Singapore population (expected frequency distribution). To answer this question, we will conduct a chi-square test of goodness of fit.</p>
</div>
<div id="section-conducting-and-interpreting-the-chi-square-test-of-goodness-of-fit" class="section level3 hasAnchor" number="8.11.2">
<h3><span class="header-section-number">8.11.2</span> Conducting and Interpreting the Chi-Square Test of Goodness of Fit<a href="section-hypotest.html#section-conducting-and-interpreting-the-chi-square-test-of-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we need the observed frequencies for men and women separately.</p>
<div class="sourceCode" id="section-cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb158-1"><a href="section-hypotest.html#section-cb158-1" tabindex="-1"></a><span class="co"># Observed frequencies for men and women (i.e., number of men and women in our study) </span></span>
<span id="section-cb158-2"><a href="section-hypotest.html#section-cb158-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="section-cb158-3"><a href="section-hypotest.html#section-cb158-3" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span> </span>
<span id="section-cb158-4"><a href="section-hypotest.html#section-cb158-4" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
## # Groups:   gender [2]
##   gender     n
##   &lt;fct&gt;  &lt;int&gt;
## 1 male     168
## 2 female   175</code></pre>
<p>The descriptives above indicate that there are 168 males and 175 females. We want to know whether the observed frequencies are significantly different from the frequencies we expect if we have an equal proportion of men and women (expected frequencies).</p>
<div class="sourceCode" id="section-cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb160-1"><a href="section-hypotest.html#section-cb160-1" tabindex="-1"></a><span class="co"># Load package (remember to install package if you&#39;ve not done so)</span></span>
<span id="section-cb160-2"><a href="section-hypotest.html#section-cb160-2" tabindex="-1"></a><span class="co"># Note that both MASS and dplyr have the select function</span></span>
<span id="section-cb160-3"><a href="section-hypotest.html#section-cb160-3" tabindex="-1"></a><span class="co"># If you wish to use the select function, specify the package the function comes from (e.g., dplyr::select())</span></span>
<span id="section-cb160-4"><a href="section-hypotest.html#section-cb160-4" tabindex="-1"></a><span class="fu">library</span>(MASS)  </span>
<span id="section-cb160-5"><a href="section-hypotest.html#section-cb160-5" tabindex="-1"></a></span>
<span id="section-cb160-6"><a href="section-hypotest.html#section-cb160-6" tabindex="-1"></a><span class="co"># Set up the values for chisq.test()</span></span>
<span id="section-cb160-7"><a href="section-hypotest.html#section-cb160-7" tabindex="-1"></a>observedfreq <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">168</span>, <span class="dv">175</span>)  <span class="co"># observed frequencies for males and females</span></span>
<span id="section-cb160-8"><a href="section-hypotest.html#section-cb160-8" tabindex="-1"></a>expectedprop <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>)  <span class="co"># expected proportions would be 0.5 for males, 0.5 for females</span></span>
<span id="section-cb160-9"><a href="section-hypotest.html#section-cb160-9" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> observedfreq, <span class="at">p =</span> expectedprop)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observedfreq
## X-squared = 0.1428571, df = 1, p-value = 0.705457</code></pre>
<div class="sourceCode" id="section-cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb162-1"><a href="section-hypotest.html#section-cb162-1" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">. The order in which you enter the values for observedfreq and expectedprop should be the same. </span></span>
<span id="section-cb162-2"><a href="section-hypotest.html#section-cb162-2" tabindex="-1"></a><span class="co"># If the first value for observedfreq is for males, then the first value for expectedprop should be for males also. </span></span>
<span id="section-cb162-3"><a href="section-hypotest.html#section-cb162-3" tabindex="-1"></a><span class="co"># (And vice versa, of course.)</span></span></code></pre></div>
<p>Because <em>p</em> value is .705457 (greater than alpha level of .05), the results tell us that the proportion of men and women in our study is not significantly different from that in the Singapore population.</p>
</div>
<div id="section-effect-size-cohens-w" class="section level3 hasAnchor" number="8.11.3">
<h3><span class="header-section-number">8.11.3</span> Effect Size: Cohen’s w<a href="section-hypotest.html#section-effect-size-cohens-w" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The effect size usually calculated for chi-square test of goodness of fit is the Cohen’s w (omega). By convention, in psychology, <em>w</em> = 0.1 is considered a small effect size, <em>w</em> = 0.3 is considered a medium effect size, and <em>w</em> = 0.5 is considered a large effect size.</p>
<p>We can calculate Cohen’s w using the <code>cohens_w()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb163-1"><a href="section-hypotest.html#section-cb163-1" tabindex="-1"></a><span class="co"># Cohen&#39;s w</span></span>
<span id="section-cb163-2"><a href="section-hypotest.html#section-cb163-2" tabindex="-1"></a><span class="fu">cohens_w</span>(<span class="at">x =</span> observedfreq, <span class="at">p =</span> expectedprop)</span></code></pre></div>
<pre><code>## Cohen&#39;s w |       95% CI
## ------------------------
## 0.02      | [0.00, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<p>The Cohen’s w is 0.02, which is a very, very small effect size (almost negligible!).</p>
<p>As an aside, Cohen’s w has no upper bound when there are more than two categories or when the expected distribution is non-uniform. What this means is that it can be arbitrarily large. Ben-Shachar et al. (2023) proposed an adjustment to Cohen’s w, which they call fei. Unlike Cohen’s w, fei is bounded between 0 and 1.</p>
<p>To calculate fei, use the function <code>fei(x = observedfreq, p = expectedprop)</code> instead.</p>
</div>
</div>
<div id="section-chi-square-test-of-independence" class="section level2 hasAnchor" number="8.12">
<h2><span class="header-section-number">8.12</span> Chi-square Test of Independence<a href="section-hypotest.html#section-chi-square-test-of-independence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="section-when-to-use-chi-square-test-of-independence" class="section level3 hasAnchor" number="8.12.1">
<h3><span class="header-section-number">8.12.1</span> When to Use Chi-square Test of Independence<a href="section-hypotest.html#section-when-to-use-chi-square-test-of-independence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the chi-square test of independence to determine if there is a relationship between two categorical variables. (I think of this as the non-parametric version of a factorial ANOVA.)</p>
<p>Let’s say we believe that people who have children are more likely to stay married (instead of divorcing) than people who don’t have children. Put it differently, we think that whether someone is married or divorced depends on whether they have children. To test whether the relationship between the two categorical variables–marital status and whether someone has children–exists, we will conduct a chi-square test of independence.</p>
</div>
<div id="section-conducting-and-interpreting-the-chi-square-test-of-independence" class="section level3 hasAnchor" number="8.12.2">
<h3><span class="header-section-number">8.12.2</span> Conducting and Interpreting the Chi-square Test of Independence<a href="section-hypotest.html#section-conducting-and-interpreting-the-chi-square-test-of-independence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we need to filter the data such that we only have married and divorced participants.</p>
<div class="sourceCode" id="section-cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb165-1"><a href="section-hypotest.html#section-cb165-1" tabindex="-1"></a><span class="co"># Filter (keep) only divorced and married participants </span></span>
<span id="section-cb165-2"><a href="section-hypotest.html#section-cb165-2" tabindex="-1"></a>div_and_mar_only <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="section-cb165-3"><a href="section-hypotest.html#section-cb165-3" tabindex="-1"></a>  <span class="fu">filter</span>(marital_status <span class="sc">==</span> <span class="st">&quot;married&quot;</span> <span class="sc">|</span> marital_status <span class="sc">==</span> <span class="st">&quot;divorced&quot;</span>) </span>
<span id="section-cb165-4"><a href="section-hypotest.html#section-cb165-4" tabindex="-1"></a></span>
<span id="section-cb165-5"><a href="section-hypotest.html#section-cb165-5" tabindex="-1"></a><span class="co"># Drop the &quot;widowed&quot; level for marital status since it is now redundant</span></span>
<span id="section-cb165-6"><a href="section-hypotest.html#section-cb165-6" tabindex="-1"></a>div_and_mar_only<span class="sc">$</span>marital_status <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(div_and_mar_only<span class="sc">$</span>marital_status)</span></code></pre></div>
<p>Then, we perform the chi-square test of independence.</p>
<div class="sourceCode" id="section-cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb166-1"><a href="section-hypotest.html#section-cb166-1" tabindex="-1"></a><span class="co"># Get the observed frequencies for each cell and save it as observedfreq</span></span>
<span id="section-cb166-2"><a href="section-hypotest.html#section-cb166-2" tabindex="-1"></a>observedfreq1 <span class="ot">&lt;-</span> div_and_mar_only <span class="sc">%&gt;%</span> </span>
<span id="section-cb166-3"><a href="section-hypotest.html#section-cb166-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(marital_status, have_children) <span class="sc">%&gt;%</span> </span>
<span id="section-cb166-4"><a href="section-hypotest.html#section-cb166-4" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="section-cb166-5"><a href="section-hypotest.html#section-cb166-5" tabindex="-1"></a></span>
<span id="section-cb166-6"><a href="section-hypotest.html#section-cb166-6" tabindex="-1"></a><span class="co"># Perform the chi-square test of independence</span></span>
<span id="section-cb166-7"><a href="section-hypotest.html#section-cb166-7" tabindex="-1"></a><span class="fu">chisq.test</span>(observedfreq1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  observedfreq1
## X-squared = 1.689424, df = 1, p-value = 0.193677</code></pre>
<div class="sourceCode" id="section-cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb168-1"><a href="section-hypotest.html#section-cb168-1" tabindex="-1"></a><span class="co"># chisq.test cannot be conducted on a list</span></span>
<span id="section-cb168-2"><a href="section-hypotest.html#section-cb168-2" tabindex="-1"></a><span class="co"># So the following wouldn&#39;t work since it gives you a list and not a matrix. </span></span>
<span id="section-cb168-3"><a href="section-hypotest.html#section-cb168-3" tabindex="-1"></a></span>
<span id="section-cb168-4"><a href="section-hypotest.html#section-cb168-4" tabindex="-1"></a>observedfreq2 <span class="ot">&lt;-</span> div_and_mar_only <span class="sc">%&gt;%</span> </span>
<span id="section-cb168-5"><a href="section-hypotest.html#section-cb168-5" tabindex="-1"></a>  <span class="fu">group_by</span>(marital_status, have_children) <span class="sc">%&gt;%</span> </span>
<span id="section-cb168-6"><a href="section-hypotest.html#section-cb168-6" tabindex="-1"></a>  <span class="fu">count</span>() </span>
<span id="section-cb168-7"><a href="section-hypotest.html#section-cb168-7" tabindex="-1"></a></span>
<span id="section-cb168-8"><a href="section-hypotest.html#section-cb168-8" tabindex="-1"></a><span class="co"># Check type for observedfreq2</span></span>
<span id="section-cb168-9"><a href="section-hypotest.html#section-cb168-9" tabindex="-1"></a><span class="fu">typeof</span>(observedfreq2)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>The chi-square test of independence results indicate that there is no significant difference in marital status for people who have children and those who don’t (<em>p</em> = .19). This means that whether a person is married or divorced does not depend on whether they have children. In other words, marital status is INDEPENDENT of having children.</p>
</div>
<div id="section-effect-size-phi" class="section level3 hasAnchor" number="8.12.3">
<h3><span class="header-section-number">8.12.3</span> Effect Size: Phi<a href="section-hypotest.html#section-effect-size-phi" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The effect size usually calculated for a 2 x 2 table is phi. (A 2 x 2 table is one in which each of the two variables has two categories.) By convention, in psychology, phi = 0.1 is considered a small effect size, phi = 0.3 is considered a medium effect size, and phi = 0.5 is considered a large effect size.</p>
<p>We can calculate phi using the <code>phi()</code> function from the <code>effectsize</code> package.</p>
<div class="sourceCode" id="section-cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="section-cb170-1"><a href="section-hypotest.html#section-cb170-1" tabindex="-1"></a><span class="co"># phi</span></span>
<span id="section-cb170-2"><a href="section-hypotest.html#section-cb170-2" tabindex="-1"></a><span class="fu">phi</span>(<span class="at">x =</span> observedfreq1)</span></code></pre></div>
<pre><code>## Phi (adj.) |       95% CI
## -------------------------
## 0.07       | [0.00, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<p>Phi is 0.07, which is a small effect size.</p>
<p>As an aside, <code>phi</code> is used for a 2 x 2 table. If you have a larger table (e.g., 2 x 3 or 3 x 4), then use Cramer’s V. To calculate Cramer’s V, use the function <code>cramers_v(x = observedfreq1)</code> instead.</p>
</div>
</div>
<div id="section-next-steps" class="section level2 hasAnchor" number="8.13">
<h2><span class="header-section-number">8.13</span> Next steps<a href="section-hypotest.html#section-next-steps" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Congratulations!!! You’ve come to the end of the hypothesis testing section and the end of this companion website! I really hope this has convinced you that R is manageable and not as scary as you thought! :)</p>
<p>What remains is… practice, practice, practice! “But where am I gonna find the datasets to practice on?”, I hear you wail. Well, here’s a start: <a href="https://www.openintro.org/data/">https://www.openintro.org/data/</a>!</p>
<p>Enjoy~! :)</p>

<p>
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::prepare_tutorial_state(session)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::i18n_observe_tutorial_language(input, session)
</script>


<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::event_trigger(session, "session_stop")
      })
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-two-plus-two-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-two-plus-two-code-editor`)), session)
output$`tutorial-exercise-two-plus-two-output` <- renderUI({
  `tutorial-exercise-two-plus-two-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_cache(structure(list(label = "two-plus-two", global_setup = NULL, setup = NULL, 
    chunks = list(list(label = "two-plus-two", code = "", opts = list(
        label = "\"two-plus-two\"", exercise = "TRUE"), engine = "r")), 
    code_check = NULL, error_check = NULL, check = NULL, solution = NULL, 
    tests = NULL, options = list(eval = FALSE, echo = TRUE, results = "markup", 
        tidy = FALSE, tidy.opts = NULL, collapse = FALSE, prompt = FALSE, 
        comment = NA, highlight = FALSE, size = "normalsize", 
        background = "#F7F7F7", strip.white = TRUE, cache = 0, 
        cache.path = "PSYC208_cache/html/", cache.vars = NULL, 
        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, 
        cache.rebuild = FALSE, fig.keep = "high", fig.show = "asis", 
        fig.align = "default", fig.path = "PSYC208_files/figure-html/", 
        dev = "png", dev.args = NULL, dpi = 192, fig.ext = "png", 
        fig.width = 7, fig.height = 5, fig.env = "figure", fig.cap = NULL, 
        fig.scap = NULL, fig.lp = "fig:", fig.subcap = NULL, 
        fig.pos = "", out.width = 672, out.height = NULL, out.extra = NULL, 
        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, 
        aniopts = "controls,loop", warning = TRUE, error = FALSE, 
        message = TRUE, render = NULL, ref.label = NULL, child = NULL, 
        engine = "r", split = FALSE, include = TRUE, purl = TRUE, 
        label = "two-plus-two", exercise = TRUE, code = "", out.width.px = 672, 
        out.height.px = 480, params.src = "two-plus-two, exercise=TRUE", 
        fig.num = 0L, exercise.df_print = "default", exercise.checker = "NULL"), 
    engine = "r", version = "4"), class = c("r", "tutorial_exercise"
)))
</script>
</p>
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["fuse"]},{"type":"character","attributes":{},"value":["6.4.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["href"]}},"value":[{"type":"character","attributes":{},"value":["https://cdn.jsdelivr.net/npm/fuse.js@6.4.6"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["dist/fuse.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["gitbook"]},{"type":"character","attributes":{},"value":["2.6.7"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["resources/gitbook"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/app.min.js","js/clipboard.min.js","js/plugin-search.js","js/plugin-sharing.js","js/plugin-fontsettings.js","js/plugin-bookdown.js","js/jquery.highlight.js","js/plugin-clipboard.js"]},{"type":"character","attributes":{},"value":["css/style.css","css/plugin-table.css","css/plugin-bookdown.css","css/plugin-highlight.css","css/plugin-search.css","css/plugin-fontsettings.css","css/plugin-clipboard.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["bookdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.37"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["anchor-sections"]},{"type":"character","attributes":{},"value":["1.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/anchor-sections"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["anchor-sections.js"]},{"type":"character","attributes":{},"value":["anchor-sections.css","anchor-sections-hash.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.21"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["6.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.min.css","css/v4-shims.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["fontawesome"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.5.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["5.5.2"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.5"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.11.5"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.11.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.5"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.5"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["2.0.10"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.5"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101]}},"value":[{"type":"character","attributes":{},"value":["abind","base","bayestestR","bit","bit64","bookdown","bslib","cachem","car","carData","cli","codetools","colorspace","compiler","crayon","datasets","datawizard","digest","dplyr","effectsize","ellipsis","emmeans","estimability","evaluate","fansi","farver","fastmap","fontawesome","forcats","generics","ggplot2","glue","graphics","grDevices","grid","gtable","highr","hms","htmltools","htmlwidgets","httpuv","insight","jquerylib","jsonlite","knitr","labeling","later","lattice","learnr","lifecycle","lubridate","magrittr","MASS","Matrix","methods","mime","mnormt","multcomp","munsell","mvtnorm","nlme","parallel","parameters","pillar","pkgconfig","promises","psych","purrr","R6","Rcpp","readr","rlang","rmarkdown","rprojroot","rstudioapi","sandwich","sass","scales","shiny","splines","stats","stringi","stringr","survival","TH.data","tibble","tidyr","tidyselect","tidyverse","timechange","tools","tzdb","utf8","utils","vctrs","vroom","withr","xfun","xtable","yaml","zoo"]},{"type":"character","attributes":{},"value":["1.4-5","4.3.0","0.13.1","4.0.5","4.0.5","0.37","0.4.2","1.0.8","3.1-2","3.0-5","3.6.1","0.2-19","2.1-0","4.3.0","1.5.2","4.3.0","0.9.1","0.6.31","1.1.2","0.8.6","0.3.2","1.10.0","1.4.1","0.21","1.0.4","2.1.1","1.1.1","0.5.1","1.0.0","0.1.3","3.4.2","1.6.2","4.3.0","4.3.0","4.3.0","0.3.3","0.10","1.1.3","0.5.5","1.6.2","1.6.11","0.19.7","0.1.4","1.8.4","1.43","0.4.2","1.3.1","0.21-8","0.11.5","1.0.3","1.9.2","2.0.3","7.3-60","1.5-4","4.3.0","0.12","2.1.1","1.4-25","0.5.0","1.2-2","3.1-162","4.3.0","0.21.1","1.9.0","2.0.3","1.2.0.1","2.4.6.26","1.0.1","2.5.1","1.0.10","2.1.4","1.1.1","2.21","2.0.3","0.14","3.0-2","0.4.6","1.2.1","1.7.4.1","4.3.0","4.3.0","1.7.12","1.5.0","3.5-5","1.1-2","3.2.1","1.3.0","1.2.0","2.0.0","0.2.0","4.3.0","0.4.0","1.2.3","4.3.0","0.6.2","1.6.3","2.5.0","0.39","1.8-4","2.3.7","1.8-12"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="section-tha3.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/hueywoon/assignment/blob/master/07-hypotesting.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
